! Computed, eXact, Epsilon
PURE FUNCTION QAE(C, X, E)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(REAL128), PARAMETER :: ZERO = 0.0_REAL128
  REAL(REAL128), INTENT(IN) :: C, X, E
  REAL(REAL128) :: QAE
  QAE = C - X
  IF ((QAE .NE. ZERO) .OR. (E .NE. ZERO)) QAE = QAE / E
END FUNCTION QAE
