PROGRAM JSVDT
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  INTERFACE
     FUNCTION CGICMAIN(ARGC, ARGV) BIND(C,NAME='cgicMain')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(KIND=c_int), INTENT(IN), VALUE :: ARGC
       TYPE(c_ptr), INTENT(IN) :: ARGV(ARGC)
       INTEGER(KIND=c_int) :: CGICMAIN
     END FUNCTION CGICMAIN
  END INTERFACE
  INTERFACE
     FUNCTION CGIMAIN(U, V) BIND(C,NAME='cgiMain')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(KIND=c_int), INTENT(IN), VALUE :: U, V
       INTEGER(KIND=c_int) :: CGIMAIN
     END FUNCTION CGIMAIN
  END INTERFACE
  INTEGER, PARAMETER :: ARGLEN = 131072
  CHARACTER(LEN=ARGLEN,KIND=c_char), ALLOCATABLE, TARGET :: ARGV0
  TYPE(c_ptr) :: ARGV(1)
  INTEGER :: RET, U
  IF (COMMAND_ARGUMENT_COUNT() .GE. 0) THEN
     OPEN(NEWUNIT=U, STATUS='SCRATCH', ACTION='WRITE', ACCESS='SEQUENTIAL', FORM='FORMATTED')
     ALLOCATE(ARGV0)
     CALL GET_COMMAND_ARGUMENT(0, ARGV0)
     ARGV0 = TRIM(ARGV0)//c_null_char
     ARGV(1) = C_LOC(ARGV0)
     RET = INT(CGICMAIN(1_c_int, ARGV))
     DEALLOCATE(ARGV0)
     IF (RET .EQ. 0) RET = INT(CGIMAIN(INT(U,c_int), INT(FNUM(U),c_int)))
     CLOSE(U)
  END IF
END PROGRAM JSVDT
