!  IN: GS = max sweeps, IX(1) = trace unit, INFO
! OUT: GS: backscale SV by 2**-GS, INFO: #sweeps
SUBROUTINE CJSVDP(M, N, G, LDG, V, LDV, JPOS, SV, GS, IX, WRK, RWRK, TBL, ORD, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE JSTEP(J, N, S, T, P, O, R, INFO)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: J, N, S, T, P, O(2,*)
       INTEGER, INTENT(OUT) :: R(2,P), INFO
     END SUBROUTINE JSTEP
  END INTERFACE
  INTERFACE
#ifdef _OPENMP
     SUBROUTINE CINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
#else
     PURE SUBROUTINE CINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDV
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: V(LDV,N)
       REAL(KIND=REAL32), INTENT(OUT) :: SV(N)
       INTEGER, INTENT(OUT) :: IX(N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CINISX
  END INTERFACE
  INTERFACE
#ifdef _OPENMP
     SUBROUTINE CSCALG(M, N, G, LDG, GX, GS, INFO)
#else
     PURE SUBROUTINE CSCALG(M, N, G, LDG, GX, GS, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(INOUT) :: GX
       INTEGER, INTENT(INOUT) :: GS, INFO
     END SUBROUTINE CSCALG
  END INTERFACE
  INTERFACE
#ifdef _OPENMP
     SUBROUTINE CPRCYC(M, N, G, LDG, JPOS, SV, IX, WRK, RWRK, INFO)
#else
     PURE SUBROUTINE CPRCYC(M, N, G, LDG, JPOS, SV, IX, WRK, RWRK, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, JPOS
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       COMPLEX(KIND=REAL32), INTENT(OUT) :: WRK(M,N)
       REAL(KIND=REAL32), INTENT(OUT) :: SV(N), RWRK(N)
       INTEGER, INTENT(INOUT) :: IX(N), INFO
     END SUBROUTINE CPRCYC
  END INTERFACE
  INTERFACE
     SUBROUTINE CTRNSP(M, N, G, LDG, V, LDV, SV, GX, P, Q, TOL, IX, WRK, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDV, P, Q, IX(N)
       COMPLEX(KIND=REAL32), INTENT(INOUT) :: G(LDG,N), V(LDV,N), TOL
       COMPLEX(KIND=REAL32), INTENT(OUT) :: WRK(M,N)
       REAL(KIND=REAL32), INTENT(INOUT) :: SV(N), GX
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE CTRNSP
  END INTERFACE
  INTERFACE
     SUBROUTINE STRACK(N, SV, GX, GS, SWP, NTR, U)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, GS, SWP, NTR, U
       REAL(KIND=REAL32), INTENT(IN) :: SV(N), GX
     END SUBROUTINE STRACK
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K, EPS = EPSILON(EPS) / 2
  INTEGER, INTENT(IN) :: M, N, LDG, LDV, JPOS, TBL(2,*)
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(OUT) :: V(LDV,N), WRK(M,N)
  REAL(KIND=K), INTENT(OUT) :: SV(N), RWRK(N)
  INTEGER, INTENT(INOUT) :: GS, IX(N), ORD(2,*), INFO
  COMPLEX(KIND=K) :: Z
  REAL(KIND=K) :: GX, TOL, X, Y
  INTEGER(KIND=INT64) :: TT
  INTEGER :: L, O, P, Q, R, S, T, U, W, ST, TP, TS
#define HINISX CINISX
#define HSCALG CSCALG
#define HPRCYC CPRCYC
#define HTRNSP CTRNSP
#define GTRACK STRACK
#define GSQRT SQRT
#include "hjsvdp.f90"
END SUBROUTINE CJSVDP
