SUBROUTINE CLJAU2(A11, A22, A21R, A21I, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_CLJEV2(A11, A22, A21R, A21I, CS, SNR, SNI, L1, L2, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_float
       REAL(KIND=c_float), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_float), INTENT(OUT) :: CS, SNR, SNI, L1, L2
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_CLJEV2
     END FUNCTION PVN_CLJEV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22
  REAL(KIND=K), INTENT(IN) :: A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: L1, L2
  INTEGER :: S
  INTEGER(KIND=c_int) :: ES, RT
#define LJU2 PVN_CLJEV2
#include "hljau2.f90"
END SUBROUTINE CLJAU2
