SUBROUTINE CLJAV2(A11, A22, A21R, A21I, CH, SHR, SHI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#ifdef USE_IEEE_INTRINSIC
#define SFMA IEEE_FMA
#else
  INTERFACE
     PURE FUNCTION SFMA(A, B, C) BIND(C,NAME='fmaf')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN), VALUE :: A, B, C
       REAL(KIND=REAL32) :: SFMA
     END FUNCTION SFMA
  END INTERFACE
#endif
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       IMPLICIT NONE
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTERFACE
     FUNCTION PVN_CLJV2(A11, A22, A21R, A21I, CH, SHR, SHI, TH, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_float
       REAL(KIND=c_float), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_float), INTENT(OUT) :: CH, SHR, SHI
       REAL(KIND=c_float), INTENT(INOUT) :: TH
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_CLJV2
     END FUNCTION PVN_CLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22, CH
  REAL(KIND=K), INTENT(IN) :: A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: SHR, SHI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: A, TH
  INTEGER(KIND=c_int) :: ES, RT
#define GFMA SFMA
#define LJV2 PVN_CLJV2
#include "hljav2.f90"
END SUBROUTINE CLJAV2
