SUBROUTINE CLJTV2(A11, A22, A21R, A21I, CH, THR, THI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_CLJV2(A11, A22, A21R, A21I, CH, THR, THI, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_float
       REAL(KIND=c_float), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_float), INTENT(OUT) :: CH, THR, THI, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_CLJV2
     END FUNCTION PVN_CLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22
  REAL(KIND=K), INTENT(INOUT) :: A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CH, THR, THI
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
#define LJV2 PVN_CLJV2
#include "hljtv2.f90"
END SUBROUTINE CLJTV2
