SUBROUTINE CLJU2(A11, A22, A21R, A21I, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32, ONE = 1.0_REAL32
  REAL(KIND=REAL32), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=REAL32), INTENT(OUT) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_CLJEU2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_CLJEU2(A11, A22, A21R, A21I, CS, SNR, SNI, ES))
  INCLUDE 'hlju2.f90'
END SUBROUTINE CLJU2
