SUBROUTINE CLJV2(A11, A22, A21R, A21I, CH, SHR, SHI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       IMPLICIT NONE
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), PARAMETER :: CUTTH = 4.0_K / 5.0_K
  REAL(KIND=K), PARAMETER :: CUTCH = 5.0_K / 3.0_K
  REAL(KIND=K), PARAMETER :: CUTSH = 4.0_K / 3.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CH, SHR, SHI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: A
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_CLJV2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_CLJV2(A11, A22, A21R, A21I, CH, SHR, SHI, ES))
  INCLUDE 'hljv2.f90'
END SUBROUTINE CLJV2
