PURE FUNCTION CNRMF(M, X)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       IMPLICIT NONE
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_float) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: CNRMF
  INTEGER :: I
  CNRMF = ZERO
  IF (M .LE. 0) RETURN
  CNRMF = CR_HYPOT(REAL(X(1)), AIMAG(X(1)))
  DO I = 2, M
     CNRMF = CR_HYPOT(CNRMF, CR_HYPOT(REAL(X(I)), AIMAG(X(I))))
  END DO
END FUNCTION CNRMF
