PURE SUBROUTINE CPRCYC(M, N, G, LDG, JPOS, SV, IX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE CCNRMF(M, N, G, LDG, SV, IX, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, IX(N)
       COMPLEX(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: SV(N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE CCNRMF
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SNSORT(N, JPOS, SV, IX, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, JPOS
       REAL(KIND=REAL32), INTENT(INOUT) :: SV(N)
       INTEGER, INTENT(INOUT) :: IX(N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE SNSORT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, N, LDG, JPOS
  COMPLEX(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(OUT) :: SV(N)
  INTEGER, INTENT(INOUT) :: IX(N), INFO
#ifndef NDEBUG
  IF ((JPOS .LT. 0) .OR. (JPOS .GT. N)) INFO = -5
  IF (LDG .LT. M) INFO = -4
  IF (N .LT. 0) INFO = -2
  IF (M .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
#endif
  IF (INFO .NE. 0) CALL CCNRMF(M, N, G, LDG, SV, IX, INFO)
#ifndef NDEBUG
  IF (INFO .NE. 0) THEN
     INFO = -6
     RETURN
  END IF
#endif
  CALL SNSORT(N, JPOS, SV, IX, INFO)
#ifndef NDEBUG
  IF (INFO .LT. 0) THEN
     INFO = -7
     RETURN
  END IF
#endif
END SUBROUTINE CPRCYC
