SUBROUTINE CRN(M, N, A)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N
  REAL(KIND=REAL32), INTENT(OUT) :: A(2*M,N)
  CALL RANDOM_NUMBER(A)
END SUBROUTINE CRN
