PURE SUBROUTINE CRTT(M, X, Y, CS, TNR, TNI, GX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       COMPLEX(KIND=REAL32), INTENT(IN) :: A, B, C
       COMPLEX(KIND=REAL32) :: CFMA
     END FUNCTION CFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(INOUT) :: X(M), Y(M)
  REAL(KIND=K), INTENT(IN) :: CS, TNR, TNI
  REAL(KIND=K), INTENT(INOUT) :: GX
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: TN, NT, XX, YY
  INTEGER :: I
#define HFMA CFMA
#include "hrtt.f90"
END SUBROUTINE CRTT
