PURE SUBROUTINE CRTVH(N, X, Y, CH, SHR, SHI, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#ifdef USE_IEEE_INTRINSIC
#define SFMA IEEE_FMA
#else
  INTERFACE
     PURE FUNCTION SFMA(A, B, C) BIND(C,NAME='fmaf')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN), VALUE :: A, B, C
       REAL(KIND=REAL32) :: SFMA
     END FUNCTION SFMA
  END INTERFACE
#endif
#define CFMA(A,B,C) CMPLX(SFMA(REAL(A),REAL(B),SFMA(-AIMAG(A),AIMAG(B),REAL(C))),SFMA(REAL(A),AIMAG(B),SFMA(AIMAG(A),REAL(B),AIMAG(C))),REAL32)
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N
  COMPLEX(KIND=K), INTENT(INOUT) :: X(N), Y(N)
  REAL(KIND=K), INTENT(IN) :: CH, SHR, SHI
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: SH, HS, XX, YY
  INTEGER :: I
#define HFMA CFMA
#include "hrtvh.f90"
END SUBROUTINE CRTVH
