PURE SUBROUTINE CRTVT(N, X, Y, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N
  COMPLEX(KIND=K), INTENT(INOUT) :: X(N), Y(N)
  REAL(KIND=K), INTENT(IN) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: SN, HS, XX, YY
  INTEGER :: I
#include "hrtvt.f90"
END SUBROUTINE CRTVT
