FUNCTION CSDP(M, X, Y, MX, MY, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(IN) :: X(M), Y(M)
  REAL(KIND=K), INTENT(IN) :: MX, MY
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=K) :: CSDP
  INTEGER :: I
  INFO = 0
  CSDP = ZERO
  IF (.NOT. (MY .GT. ZERO)) INFO = -5
  IF (.NOT. (MX .GT. ZERO)) INFO = -4
  IF (M .LT. 0) INFO = -1
  IF (INFO .NE. 0) RETURN
  DO I = 1, M
     CSDP = CSDP + (X(I) / MX) * (Y(I) / MY)
  END DO
END FUNCTION CSDP
