PROGRAM CTEST
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: CLAL = 256
  REAL(REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
  CHARACTER(LEN=CLAL) :: CLA
  REAL(c_float), PARAMETER :: HALF = 0.5_c_float
9 FORMAT(A,ES16.9E2)
CONTAINS
#include "orfile.F90"
#include "srsafe.F90"
#include "ydetm1.F90"
#include "qre.F90"
END PROGRAM CTEST
