SUBROUTINE ZTRACE(N, A, LDA, AX, AS, SWP, NTR)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDA, AS, SWP, NTR
  COMPLEX(KIND=K), INTENT(IN) :: A(LDA,N)
  REAL(KIND=K), INTENT(IN) :: AX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,A,I11,A,I6,A,ES16.9E2)') SWP, ',', NTR, ',', AS, ',', AX
  FLUSH(ERROR_UNIT)
  IF (N .LT. 1000) THEN
     I = -AS
     DO J = 1, N
        WRITE (ERROR_UNIT,'(I3,A,ES16.9E2)') J, ',', SCALE(REAL(REAL(A(J,J)), REAL64), I)
        FLUSH(ERROR_UNIT)
     END DO
  END IF
END SUBROUTINE ZTRACE
