SUBROUTINE CTRCOA(N, A, LDA, AS, S, T, U)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CNRMOA(N, A, LDA, AS)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, AS
       COMPLEX(KIND=REAL32), INTENT(IN) :: A(LDA,N)
       REAL(KIND=REAL64) :: CNRMOA
     END FUNCTION CNRMOA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDA, AS, S
  COMPLEX(KIND=K), INTENT(IN) :: A(LDA,N)
  INTEGER, INTENT(INOUT) :: T, U
  INTEGER :: NS, MD, H1
  CHARACTER(LEN=8) :: FN
  IF ((LDA .LT. N) .OR. (N .LE. 1) .OR. (N .GE. 1000)) RETURN
  IF (S .EQ. 0) THEN
     WRITE (FN,'(A,I3.3,A)') CHAR(T), N, '.csv'
     OPEN(NEWUNIT=U, IOSTAT=T, FILE=FN, STATUS='REPLACE', ACTION='WRITE', ACCESS='SEQUENTIAL', FORM='FORMATTED')
     IF (T .EQ. 0) THEN
        WRITE (U,'(A)') '"TRANSF", "SWEEP", "off(A)"'
        FLUSH(U)
     ELSE ! ERROR
        RETURN
     END IF
  END IF
  NS = (N * (N - 1)) / 2
  MD = MOD(T, NS)
  H1 = N / 2
  IF ((MD .EQ. 0) .OR. (MD .EQ. 1) .OR. (MOD(MD, H1) .EQ. 0)) THEN
     WRITE (U,'(I11,A,I3,A,ES16.9E2)') T, ',', S, ',', CNRMOA(N, A, LDA, AS)
     FLUSH(U)
  END IF
  IF (S .LT. 0) THEN
     CLOSE(U)
  ELSE ! S >= 0
     T = T + 1
  END IF
END SUBROUTINE CTRCOA
