PURE FUNCTION DFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION C_FMA(X, Y, Z) BIND(C,NAME='fma')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y, Z
       REAL(KIND=c_double) :: C_FMA
     END FUNCTION C_FMA
  END INTERFACE
  REAL(KIND=REAL64), INTENT(IN) :: A, B, C
  REAL(KIND=REAL64) :: DFMA
  DFMA = C_FMA(A, B, C)
END FUNCTION DFMA
