PROGRAM DJSVRR
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: OUTPUT_UNIT, REAL64
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: OUTPUT_UNIT, REAL64, REAL128
#endif
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: KK = c_long_double
#else
  INTEGER, PARAMETER :: KK = REAL128
#endif
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=KK), PARAMETER :: XZERO = 0.0_KK
  CHARACTER(LEN=256) :: CLA
  REAL(KIND=K), ALLOCATABLE :: G(:,:), V(:,:), U(:,:), S(:)
  REAL(KIND=KK), ALLOCATABLE :: XG(:,:), XV(:,:), XU(:,:), XS(:)
  REAL(KIND=KK) :: X, GN
  INTEGER :: M, N, I, J, L
  EXTERNAL :: BFOPEN
#ifdef __GFORTRAN__
  !$OMP DECLARE REDUCTION(HYP:REAL(KK):OMP_OUT=CR_HYPOTL(OMP_OUT,OMP_IN)) INITIALIZER(OMP_PRIV=XZERO)
#else
  !$OMP DECLARE REDUCTION(HYP:REAL(KK):OMP_OUT=CR_HYPOTQ(OMP_OUT,OMP_IN)) INITIALIZER(OMP_PRIV=XZERO)
#endif
#include "gjsvrr.F90"
9 FORMAT(I11,A,ES25.17E3)
END PROGRAM DJSVRR
