SUBROUTINE DLJTV2(A11, A22, A21, CH, TH, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_DLJV2(A11, A22, A21, CH, TH, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_double
       REAL(KIND=c_double), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_double), INTENT(OUT) :: CH, TH, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_DLJV2
     END FUNCTION PVN_DLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22
  REAL(KIND=K), INTENT(INOUT) :: A21
  REAL(KIND=K), INTENT(OUT) :: CH, TH
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
#define LJV2 PVN_DLJV2
#include "gljtv2.f90"
END SUBROUTINE DLJTV2
