SUBROUTINE DLJU2(A11, A22, A21, CS, SN, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, ONE = 1.0_REAL64
  REAL(KIND=REAL64), INTENT(IN) :: A11, A22, A21
  REAL(KIND=REAL64), INTENT(OUT) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_DLJEU2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_DLJEU2(A11, A22, A21, CS, SN, ES))
  INCLUDE 'glju2.f90'
END SUBROUTINE DLJU2
