SUBROUTINE DLJV2(A11, A22, A21, CH, SH, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_DLJV2(A11, A22, A21, CH, SH, TH, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_double
       REAL(KIND=c_double), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_double), INTENT(OUT) :: CH, SH, TH
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_DLJV2
     END FUNCTION PVN_DLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), PARAMETER :: CUTTH = 4.0_K / 5.0_K
  REAL(KIND=K), PARAMETER :: CUTCH = 5.0_K / 3.0_K
  REAL(KIND=K), PARAMETER :: CUTSH = 4.0_K / 3.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21
  REAL(KIND=K), INTENT(OUT) :: CH, SH
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: A, TH
  INTEGER(KIND=c_int) :: ES, RT
#define LJV2 PVN_DLJV2
#include "gljv2.f90"
END SUBROUTINE DLJV2
