! C += A * B
#ifdef _OPENMP
SUBROUTINE DMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#else
PURE SUBROUTINE DMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M, N, LDA, LDB, LDC
  REAL(KIND=K), INTENT(IN) :: A(LDA,M), B(LDB,N)
  REAL(KIND=K), INTENT(INOUT) :: C(LDC,N)
  INTEGER :: I, J, L
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I,J,L) SHARED(A,B,C,M,N)
  DO J = 1, N
     DO L = 1, M
        DO I = 1, N
           !DIR$ FMA
           C(I,J) = A(I,L) * B(L,J) + C(I,J)
        END DO
     END DO
  END DO
  !$OMP END PARALLEL DO
END SUBROUTINE DMMMSQ
