PURE FUNCTION DNRMOA(N, A, LDA, AS)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
#endif
  IMPLICIT NONE
#include "cr.f90"
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: KK = c_long_double
#else
  INTEGER, PARAMETER :: KK = REAL128
#endif
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=KK), PARAMETER :: ZERO = 0.0_KK
  INTEGER, INTENT(IN) :: N, LDA, AS
  REAL(KIND=K), INTENT(IN) :: A(LDA,N)
  REAL(KIND=KK) :: DNRMOA
  INTEGER :: I, J, L
  DNRMOA = ZERO
  IF (N .LE. 1) RETURN
  L = -AS
  DO J = 1, N-1
     DO I = J+1, N
        DNRMOA = CR_HYPOT(DNRMOA, SCALE(REAL(A(I,J), KK), L))
     END DO
  END DO
  DNRMOA = DNRMOA * CR_SQRT(2.0_KK)
END FUNCTION DNRMOA
