PURE FUNCTION DNRMF(M, X)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: DNRMF
  INTEGER :: I
  DNRMF = ZERO
  IF (M .LE. 0) RETURN
  DNRMF = ABS(X(1))
  DO I = 2, M
     DNRMF = CR_HYPOT(DNRMF, X(I))
  END DO
END FUNCTION DNRMF
