FUNCTION DRSAFE(U)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(c_double) :: DRSAFE
  REAL(c_double) :: RMIN, RMAX, R, A
  RMIN = TINY(A)
  A = HUGE(A)
  RMAX = SCALE(A, -2)
  DO WHILE ((.NOT. (A .GE. RMIN)) .OR. (.NOT. (A .LE. RMAX)))
     READ (U) R
     A = ABS(R)
  END DO
  DRSAFE = R
END FUNCTION DRSAFE
