FUNCTION DRSAFE(U)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(KIND=c_double) :: DRSAFE
  REAL(KIND=c_double) :: RMIN, RMAX, R
  RMIN = TINY(R)
  R = HUGE(R)
  RMAX = SCALE(R, -2)
  DO WHILE ((.NOT. (R .GE. RMIN)) .OR. (.NOT. (R .LE. RMAX)))
     READ (U) R
  END DO
  DRSAFE = R
END FUNCTION DRSAFE
