PURE SUBROUTINE DRTRH(N, A, LDA, AX, P, Q, CH, SH, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N), AX
  REAL(KIND=K), INTENT(IN) :: CH, SH
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: XX, YY
  INTEGER :: I
  INCLUDE 'grtrh.f90'
END SUBROUTINE DRTRH
