PURE SUBROUTINE DRTT(M, X, Y, CS, TN, GX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(INOUT) :: X(M), Y(M), GX
  REAL(KIND=K), INTENT(IN) :: CS, TN
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: XX, YY
  INTEGER :: I
#include "grtt.f90"
END SUBROUTINE DRTT
