PURE SUBROUTINE DRTVT(N, X, Y, CS, SN, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N
  REAL(KIND=K), INTENT(INOUT) :: X(N), Y(N)
  REAL(KIND=K), INTENT(IN) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: XX, YY, NS
  INTEGER :: I
#define GFMA DFMA
#include "grtvt.f90"
END SUBROUTINE DRTVT
