FUNCTION DSDP(M, X, Y, MX, MY, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(IN) :: X(M), Y(M), MX, MY
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: DSDP
  INTEGER :: I
  INFO = 0
  DSDP = ZERO
  IF (.NOT. (MY .GT. ZERO)) INFO = -5
  IF (.NOT. (MX .GT. ZERO)) INFO = -4
  IF (M .LT. 0) INFO = -1
  IF (INFO .NE. 0) RETURN
  DO I = 1, M
     !DIR$ FMA
     DSDP = DSDP + (X(I) / MX) * (Y(I) / MY)
  END DO
END FUNCTION DSDP
