SUBROUTINE DSWPXD(N, A, LDA, V, LDV, B, E, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE DSWPC(N, A, LDA, P, Q, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       REAL(KIND=REAL64), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DSWPC
  END INTERFACE
  INTERFACE
     SUBROUTINE DSWPR(N, A, LDA, P, Q, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       REAL(KIND=REAL64), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DSWPR
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: N, LDA, LDV, B, E
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N), V(LDV,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: X, T
  INTEGER :: J
#define SWPC DSWPC
#define SWPR DSWPR
#include "gswpxd.f90"
END SUBROUTINE DSWPXD
