SUBROUTINE DSWPR(N, A, LDA, P, Q, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: T
  INTEGER :: J
  INCLUDE 'gswpr.f90'
END SUBROUTINE DSWPR
