SUBROUTINE DTRACE(N, A, LDA, AX, AS, SWP, NTR)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL64
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL64, REAL128
#endif
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, LDA, AS, SWP, NTR
  REAL(KIND=K), INTENT(IN) :: A(LDA,N), AX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,A,I11,A,I6,A,ES25.17E3)') SWP, ',', ABS(NTR), ',', AS, ',', AX
  FLUSH(ERROR_UNIT)
  IF ((NTR .GT. 0) .AND. (N .LT. 1000)) THEN
     I = -AS
     DO J = 1, N
#ifdef __GFORTRAN__
        WRITE (ERROR_UNIT,'(I3,A,ES25.17E3)') J, ',', SCALE(REAL(A(J,J), c_long_double), I)
#else
        WRITE (ERROR_UNIT,'(I3,A,ES25.17E3)') J, ',', SCALE(REAL(A(J,J), REAL128), I)
#endif
        FLUSH(ERROR_UNIT)
     END DO
  END IF
END SUBROUTINE DTRACE
