SUBROUTINE DTRACK(N, SV, GX, GS, SWP, NTR)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL64
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL64, REAL128
#endif
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, GS, SWP, NTR
  REAL(KIND=K), INTENT(IN) :: SV(N), GX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,A,I11,A,I6,A,ES25.17E3)') SWP, ',', NTR, ',', GS, ',', GX
  FLUSH(ERROR_UNIT)
  IF (N .LT. 1000) THEN
     I = -GS
     DO J = 1, N
#ifdef __GFORTRAN__
        WRITE (ERROR_UNIT,'(I3,A,ES25.17E3)') J, ',', SCALE(REAL(SV(J), 10), I)
#else
        WRITE (ERROR_UNIT,'(I3,A,ES25.17E3)') J, ',', SCALE(REAL(SV(J), REAL128), I)
#endif
        FLUSH(ERROR_UNIT)
     END DO
  END IF
END SUBROUTINE DTRACK
