SUBROUTINE DTRACK(N, SV, GX, GS, SWP, NTR, U)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL64
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL64, REAL128
#endif
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, GS, SWP, NTR, U
  REAL(KIND=K), INTENT(IN) :: SV(N), GX
  INTEGER :: I, J
  IF (U .EQ. INPUT_UNIT) RETURN
  WRITE (U,'(I10,A,I11,A,I6,A,ES25.17E3)') SWP, ',', ABS(NTR), ',', GS, ',', GX
  FLUSH(U)
  IF ((NTR .GT. 0) .AND. (N .LT. 1000)) THEN
     I = -GS
     DO J = 1, N
#ifdef __GFORTRAN__
        WRITE (U,'(I3,A,ES25.17E3)') J, ',', SCALE(REAL(SV(J), c_long_double), I)
#else
        WRITE (U,'(I3,A,ES25.17E3)') J, ',', SCALE(REAL(SV(J), REAL128), I)
#endif
        FLUSH(U)
     END DO
  END IF
END SUBROUTINE DTRACK
