! IN: INFO & 1: hyp
!     INFO & 2: SLOW
!OUT: INFO = 0: notransf due to tol
!     INFO = 1: notransf due to identity transf
!     INFO = 2: transf
!     INFO = 3: transf, big th
SUBROUTINE DTRNSP(M, N, G, LDG, V, LDV, SV, GX, P, Q, TOL, IX, WRK, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL64
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
  INTERFACE
     PURE RECURSIVE FUNCTION DNRMF(M, X)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL64), INTENT(IN) :: X(M)
       REAL(KIND=REAL64) :: DNRMF
     END FUNCTION DNRMF
  END INTERFACE
  INTERFACE
     FUNCTION DSDP(M, X, Y, MX, MY, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       INTEGER, INTENT(INOUT) :: INFO
       REAL(KIND=REAL64), INTENT(IN) :: X(M), Y(M), MX, MY
       REAL(KIND=REAL64) :: DSDP
     END FUNCTION DSDP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DGRAM(PNF, QNF, QPS, APP, AQQ, AQP, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN) :: PNF, QNF, QPS
       REAL(KIND=REAL64), INTENT(OUT) :: APP, AQQ, AQP
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE DGRAM
  END INTERFACE
  INTERFACE
     SUBROUTINE DLJTU2(A11, A22, A21, CS, TN, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(INOUT) :: A11, A22, A21
       REAL(KIND=REAL64), INTENT(OUT) :: CS, TN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DLJTU2
  END INTERFACE
  INTERFACE
     SUBROUTINE DLJTV2(A11, A22, A21, CH, TH, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(INOUT) :: A11, A22, A21, CH
       REAL(KIND=REAL64), INTENT(OUT) :: TH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DLJTV2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DRTT(M, X, Y, CS, TN, GX, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL64), INTENT(INOUT) :: X(M), Y(M), GX
       REAL(KIND=REAL64), INTENT(IN) :: CS, TN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DRTT
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE DRTH(M, X, Y, CH, TH, GX, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL64), INTENT(INOUT) :: X(M), Y(M), GX
       REAL(KIND=REAL64), INTENT(IN) :: CH, TH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE DRTH
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: M, N, LDG, LDV, P, Q, IX(N)
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N), V(LDV,N), SV(N), GX, TOL
  REAL(KIND=K), INTENT(OUT) :: WRK(M,N)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: QPS, APP, AQQ, AQP, C, S, T
  INTEGER :: I, J, L, O, E
#define GNRMF DNRMF
#define GSDP DSDP
#define GGRAM DGRAM
#define GLJTU2 DLJTU2
#define GLJTV2 DLJTV2
#define GRTT DRTT
#define GRTH DRTH
#define GSQRT SQRT
#define GFMA DFMA
#include "gtrnsp.f90"
END SUBROUTINE DTRNSP
