  INFO = 0
  IF (LDG .LT. M) INFO = -4
  IF (N .LT. 0) INFO = -2
  IF (M .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(J,L) SHARED(G,IX,SV,M,N) REDUCTION(MAX:INFO)
  DO J = 1, N
     L = IX(J)
     SV(J) = NRMF(M, G(1,L))
     IF (.NOT. (SV(J) .LE. HUGE(SV(J)))) INFO = MAX(INFO, J)
  END DO
  !$OMP END PARALLEL DO
