! C = A * B
PURE SUBROUTINE JMMMSQ(N, A, LDA, B, LDB, C, LDC)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = INT64
  INTEGER(KIND=K), PARAMETER :: ZERO = 0_K
  INTEGER, INTENT(IN) :: N, LDA, LDB, LDC
  INTEGER(KIND=K), INTENT(IN) :: A(LDA,N), B(LDB,N)
  INTEGER(KIND=K), INTENT(OUT) :: C(LDC,N)
  INTEGER :: I, J, L
  DO J = 1, N
     DO I = 1, N
        C(I,J) = ZERO
        DO L = 1, N
           C(I,J) = A(I,L) * B(L,J) + C(I,J)
        END DO
     END DO
  END DO
END SUBROUTINE JMMMSQ
