PURE SUBROUTINE MDSORT(N, A, LDA, V, LDV, JPOS, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE MSWPC(N, A, LDA, P, Q, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE MSWPC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MSWPR(N, A, LDA, P, Q, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE MSWPR
  END INTERFACE
  INTEGER, INTENT(IN) :: N, LDA, LDV, JPOS
  TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N), V(LDV,N)
  INTEGER, INTENT(OUT) :: INFO
  TYPE(MPFR_T) :: X
  INTEGER :: I, J, L, M
  CALL MPFR_INIT_M(X)
#define SWPC MSWPC
#define SWPR MSWPR
#include "gdsort.f90"
  CALL MPFR_CLEAR_M(X)
END SUBROUTINE MDSORT
