PROGRAM MJEVDT
  USE MPFR_F
  IMPLICIT NONE
  CHARACTER(LEN=256) :: CLA
  INTEGER :: N, JPOS, INFO, I, J
  TYPE(MPFR_T), ALLOCATABLE :: A(:,:), V(:,:), WRK(:,:)
  REAL(KIND=REAL64), ALLOCATABLE :: X(:,:)
  INTEGER(KIND=INT64) :: P
  EXTERNAL :: BFOPEN, MJEVDR
  ! read the command line arguments
  I = COMMAND_ARGUMENT_COUNT()
  IF (I .NE. 5) STOP 'mjevdt.exe N JPOS OPTS PREC FILE'
  I = 0
  CALL GET_COMMAND_ARGUMENT(1, CLA)
  READ (CLA,*) N
  IF (N .LE. 0) STOP 'N <= 0'
  CALL GET_COMMAND_ARGUMENT(2, CLA)
  READ (CLA,*) JPOS
  CALL GET_COMMAND_ARGUMENT(3, CLA)
  READ (CLA,*) INFO
  IF ((INFO .NE. 1) .AND. (INFO .NE. 3)) STOP 'OPTS'
  CALL GET_COMMAND_ARGUMENT(4, CLA)
  READ (CLA,*) P
  IF ((P .LT. 1) .OR. (P .GT. HUGE(I))) STOP 'PREC'
  CALL GET_COMMAND_ARGUMENT(5, CLA)
  IF (LEN_TRIM(CLA) .LE. 0) STOP 'FILE'
  CALL BFOPEN(TRIM(CLA)//'.A', 'RO', I, J)
  IF (J .NE. 0) STOP 'OPEN(A)'
  ALLOCATE(X(N,N))
  READ (UNIT=I, IOSTAT=J) X
  IF (J .NE. 0) STOP 'READ(A)'
  CLOSE (UNIT=I, IOSTAT=J)
  IF (J .NE. 0) STOP 'CLOSE(A)'
  IF (MPFR_INITIALIZE(P) .NE. 0) STOP 'MPFR_INITIALIZE'
  ALLOCATE(A(N,N))
  DO J = 1, N
     DO I = 1, N
        CALL MPFR_INIT_M(A(I,J))
        A(I,J) = X(I,J)
     END DO
  END DO
  ALLOCATE(V(N,N))
  DO J = 1, N
     DO I = 1, N
        CALL MPFR_INIT_M(V(I,J))
     END DO
  END DO
  ALLOCATE(WRK(N,N))
  DO J = 1, N
     DO I = 1, N
        CALL MPFR_INIT_M(WRK(I,J))
     END DO
  END DO
  IF (JPOS .LT. 0) THEN
     P = JPOS
     JPOS = -(JPOS + 1)
  ELSE ! JPOS >= 0
     P = 0_INT64
  END IF
  IF ((JPOS .LT. 0) .OR. (JPOS .GT. N)) STOP 'JPOS'
  WRK(1,1) = P
  CALL MJEVDR(N, A, N, V, N, JPOS, WRK, INFO)
  P = WRK(1,1)
  WRITE (OUTPUT_UNIT,'(I2,A,I11)') INFO, ',', P
  FLUSH(OUTPUT_UNIT)
  DO J = N, 1, -1
     DO I = N, 1, -1
        CALL MPFR_CLEAR_M(WRK(I,J))
     END DO
  END DO
  DEALLOCATE(WRK)
  DO J = N, 1, -1
     DO I = N, 1, -1
        CALL MPFR_CLEAR_M(V(I,J))
     END DO
  END DO
  DEALLOCATE(V)
  DO J = N, 1, -1
     DO I = N, 1, -1
        CALL MPFR_CLEAR_M(A(I,J))
     END DO
  END DO
  DEALLOCATE(A)
  CALL MPFR_FINALIZE()
  DEALLOCATE(X)
END PROGRAM MJEVDT
