SUBROUTINE MLJAV2(A11, A22, A21, CH, SH, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ONE = 1.0_K, MTWO = -2.0_K
  TYPE(MPFR_T), INTENT(INOUT) :: A11, A22, CH, SH
  TYPE(MPFR_T), INTENT(IN) :: A21
  INTEGER, INTENT(INOUT) :: INFO
  TYPE(MPFR_T) :: AA, T2, T1
  INTEGER(KIND=MPFR_PREC_KIND) :: A21P
  CALL MPFR_INIT_M(AA, A21%MPFR_PREC)
  A21P = MAX(CH%MPFR_PREC, SH%MPFR_PREC)
  CALL MPFR_INIT_M(T2, A21P)
  CALL MPFR_INIT_M(T1, A21P)
  CH = ONE
  CALL MPFR_SET_ZERO(SH, SH%TAG)
  A21P = INT(MPFR_CMP(A21, SH), MPFR_PREC_KIND)
  IF (A21P .EQ. 0_MPFR_PREC_KIND) THEN
     INFO = IOR(INFO, 4)
     RETURN
  END IF
  CALL MPFR_ABS_F(AA, A21)
  CALL MPFR_ADD_F(T2, A11, A22)
  CALL MPFR_MUL_D_F(T1, AA, MTWO)
  CALL MPFR_DIV_F(T2, T1, T2)
  CALL MPFR_NEG_F(SH, T2)
  CALL MPFR_FMA_F(T1, SH, T2, CH)
  CALL MPFR_SQRT_F(T1, T1)
  CALL MPFR_ADD_F(T1, T1, CH)
  CALL MPFR_DIV_F(T1, T2, T1)
  CALL MPFR_NEG_F(SH, T1)
  CALL MPFR_FMA_F(CH, SH, T1, CH)
  CALL MPFR_REC_SQRT_F(CH, CH)
  CALL MPFR_FMA_F(A11, T1, AA, A11)
  CALL MPFR_FMA_F(A22, T1, AA, A22)
  IF (A21P .GT. 0_MPFR_PREC_KIND) CALL MPFR_SET_M(SH, T1)
  CALL MPFR_CLEAR_M(T1)
  CALL MPFR_CLEAR_M(T2)
  CALL MPFR_CLEAR_M(AA)
END SUBROUTINE MLJAV2
