PURE SUBROUTINE MRTLT(N, A, LDA, P, Q, CS, SN, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
  TYPE(MPFR_T), INTENT(IN) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  TYPE(MPFR_T) :: XX, YY, HS
  INTEGER :: J
  IF (N .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
  IF (IAND(INFO, 4) .EQ. 0) THEN
     CALL MPFR_INIT_M(XX)
     CALL MPFR_INIT_M(YY)
     CALL MPFR_INIT_M(HS)
     CALL MPFR_NEG_F(HS, SN)
     ! SN => TG
     DO J = 1, P-1
        CALL MPFR_FMA_F(XX, SN, A(Q,J), A(P,J))
        CALL MPFR_MUL_F(XX, CS, XX)
        CALL MPFR_FMA_F(YY, HS, A(P,J), A(Q,J))
        CALL MPFR_MUL_F(YY, CS, YY)
        A(P,J) = XX
        A(Q,J) = YY
     END DO
     CALL MPFR_FMA_F(YY, HS, A(P,P), A(Q,P))
     CALL MPFR_MUL_F(A(Q,P), CS, YY)
     CALL MPFR_CLEAR_M(HS)
     CALL MPFR_CLEAR_M(YY)
     CALL MPFR_CLEAR_M(XX)
  END IF
END SUBROUTINE MRTLT
