PURE SUBROUTINE MRTRT(N, A, LDA, P, Q, CS, SN, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
  TYPE(MPFR_T), INTENT(IN) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  TYPE(MPFR_T) :: XX, YY, HS
  INTEGER :: I
  IF (N .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
  IF (IAND(INFO, 4) .EQ. 0) THEN
     CALL MPFR_INIT_M(XX)
     CALL MPFR_INIT_M(YY)
     CALL MPFR_INIT_M(HS)
     CALL MPFR_NEG_F(HS, SN, MPFR_RNDN)
     ! SN => TG
     DO I = P+1, Q-1
        CALL MPFR_FMA_F(XX, A(Q,I), SN, A(I,P), MPFR_RNDN)
        CALL MPFR_MUL_F(XX, XX, CS, MPFR_RNDN)
        CALL MPFR_FMA_F(YY, A(I,P), HS, A(Q,I), MPFR_RNDN)
        CALL MPFR_MUL_F(YY, YY, CS, MPFR_RNDN)
        A(I,P) = XX
        A(Q,I) = YY
     END DO
     CALL MPFR_FMA_F(XX, A(Q,Q), SN, A(Q,P), MPFR_RNDN)
     CALL MPFR_MUL_F(A(Q,P), XX, CS, MPFR_RNDN)
     DO I = Q+1, N
        CALL MPFR_FMA_F(XX, A(I,Q), SN, A(I,P), MPFR_RNDN)
        CALL MPFR_MUL_F(XX, XX, CS, MPFR_RNDN)
        CALL MPFR_FMA_F(YY, A(I,P), HS, A(I,Q), MPFR_RNDN)
        CALL MPFR_MUL_F(YY, YY, CS, MPFR_RNDN)
        A(I,P) = XX
        A(I,Q) = YY
     END DO
     CALL MPFR_CLEAR_M(HS)
     CALL MPFR_CLEAR_M(YY)
     CALL MPFR_CLEAR_M(XX)
  END IF
END SUBROUTINE MRTRT
