PURE SUBROUTINE MRTVH(N, X, Y, CH, SH, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N
  TYPE(MPFR_T), INTENT(INOUT) :: X(N), Y(N)
  TYPE(MPFR_T), INTENT(IN) :: CH, SH
  INTEGER, INTENT(INOUT) :: INFO
  TYPE(MPFR_T) :: XX, YY
  INTEGER :: I
  IF (N .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
  IF (IAND(INFO, 4) .EQ. 0) THEN
     CALL MPFR_INIT_M(XX)
     CALL MPFR_INIT_M(YY)
     ! SH => TH
     DO I = 1, N
        CALL MPFR_FMA_F(XX, Y(I), SH, X(I), MPFR_RNDN)
        CALL MPFR_MUL_F(XX, XX, CH, MPFR_RNDN)
        CALL MPFR_FMA_F(YY, X(I), SH, Y(I), MPFR_RNDN)
        CALL MPFR_MUL_F(YY, YY, CH, MPFR_RNDN)
        X(I) = XX
        Y(I) = YY
     END DO
     CALL MPFR_CLEAR(YY)
     CALL MPFR_CLEAR(XX)
  END IF
END SUBROUTINE MRTVH
