PURE SUBROUTINE MRTVT(N, X, Y, CS, SN, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N
  TYPE(MPFR_T), INTENT(INOUT) :: X(N), Y(N)
  TYPE(MPFR_T), INTENT(IN) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  TYPE(MPFR_T) :: XX, YY, HS
  INTEGER :: I
  IF (N .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
  IF (IAND(INFO, 4) .EQ. 0) THEN
     CALL MPFR_INIT_M(XX)
     CALL MPFR_INIT_M(YY)
     CALL MPFR_INIT_M(HS)
     CALL MPFR_NEG_F(HS, SN, MPFR_RNDN)
     ! SN => TG
     DO I = 1, N
        CALL MPFR_FMA_F(XX, Y(I), SN, X(I), MPFR_RNDN)
        CALL MPFR_MUL_F(XX, XX, CS, MPFR_RNDN)
        CALL MPFR_FMA_F(YY, X(I), HS, Y(I), MPFR_RNDN)
        CALL MPFR_MUL_F(YY, YY, CS, MPFR_RNDN)
        X(I) = XX
        Y(I) = YY
     END DO
     CALL MPFR_CLEAR(HS)
     CALL MPFR_CLEAR(YY)
     CALL MPFR_CLEAR(XX)
  END IF
END SUBROUTINE MRTVT
