PURE SUBROUTINE MSWPC(N, A, LDA, P, Q, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
  INTEGER, INTENT(OUT) :: INFO
  INTEGER :: I
  INFO = 0
  IF ((Q .LE. 0) .OR. (Q .GT. N)) INFO = -5
  IF ((P .LE. 0) .OR. (P .GT. N)) INFO = -4
  IF (LDA .LE. 0) INFO = -3
  IF ((N .LE. 0) .OR. (N .GT. LDA)) INFO = -1
  IF (INFO .NE. 0) RETURN
  IF (P .EQ. Q) RETURN
  DO I = P, Q-1
     CALL MPFR_SWAP_M(A(I,P), A(Q,I))
  END DO
  DO I = Q, N
     CALL MPFR_SWAP_M(A(I,P), A(I,Q))
  END DO
END SUBROUTINE MSWPC
