! IN: INFO & 1: sin => tan
!     INFO & 2: hyp
!OUT: INFO = 0: notransf
!     INFO = 1: swap only
!     INFO = 2: transf, no downscaling of A
!     INFO = 3: transf with downscaling of A
SUBROUTINE MTRANA(N, A, LDA, V, LDV, P, Q, TOL, INFO)
  USE MPFR_F
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE MLJAU2(A11, A22, A21, CS, SN, INFO)
       USE MPFR_F
       IMPLICIT NONE
       TYPE(MPFR_T), INTENT(INOUT) :: A11, A22, CS, SN
       TYPE(MPFR_T), INTENT(IN) :: A21
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MLJAU2
  END INTERFACE
  INTERFACE
     SUBROUTINE MLJAV2(A11, A22, A21, CH, SH, INFO)
       USE MPFR_F
       IMPLICIT NONE
       TYPE(MPFR_T), INTENT(INOUT) :: A11, A22, CH, SH
       TYPE(MPFR_T), INTENT(IN) :: A21
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MLJAV2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MRTVT(N, X, Y, CS, SN, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       TYPE(MPFR_T), INTENT(INOUT) :: X(N), Y(N)
       TYPE(MPFR_T), INTENT(IN) :: CS, SN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MRTVT
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MRTVH(N, X, Y, CH, SH, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       TYPE(MPFR_T), INTENT(INOUT) :: X(N), Y(N)
       TYPE(MPFR_T), INTENT(IN) :: CH, SH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MRTVH
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MRTLT(N, A, LDA, P, Q, CS, SN, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
       TYPE(MPFR_T), INTENT(IN) :: CS, SN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MRTLT
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MRTLH(N, A, LDA, P, Q, CH, SH, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
       TYPE(MPFR_T), INTENT(IN) :: CH, SH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MRTLH
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MRTRT(N, A, LDA, P, Q, CS, SN, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
       TYPE(MPFR_T), INTENT(IN) :: CS, SN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MRTRT
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE MRTRH(N, A, LDA, P, Q, CH, SH, INFO)
       USE MPFR_F
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N)
       TYPE(MPFR_T), INTENT(IN) :: CH, SH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE MRTRH
  END INTERFACE
  INTEGER, INTENT(IN) :: N, LDA, LDV, P, Q
  TYPE(MPFR_T), INTENT(INOUT) :: A(LDA,N), V(LDV,N), TOL
  INTEGER, INTENT(INOUT) :: INFO
  TYPE(MPFR_T) :: A1, A2, C, S
  INTEGER :: I
  IF ((INFO .LT. 0) .OR. (INFO .GT. 3)) INFO = -9
  IF ((Q .LE. 0) .OR. (Q .GT. N)) INFO = -7
  IF ((P .LE. 0) .OR. (P .GT. N)) INFO = -6
  IF (LDV .LT. N) INFO = -5
  IF (LDA .LT. N) INFO = -3
  IF (N .LT. 0) INFO = -1
  IF (INFO .LT. 0) RETURN
  IF (N .EQ. 0) RETURN
  I = IAND(INFO, 2)
  INFO = IAND(INFO, 1)
  CALL MPFR_INIT_M(A1)
  CALL MPFR_INIT_M(A2)
  CALL MPFR_INIT_M(C)
  CALL MPFR_INIT_M(S)
  CALL MPFR_SET_M(A1, A(P,P))
  CALL MPFR_SET_M(A2, A(Q,Q))
  CALL MPFR_ABS_F(C, A1)
  CALL MPFR_ABS_F(S, A2)
  CALL MPFR_SQRT_F(C, C)
  CALL MPFR_SQRT_F(S, S)
  CALL MPFR_MUL_F(C, C, S)
  CALL MPFR_MUL_F(C, C, TOL)
  CALL MPFR_ABS_F(S, A(Q,P))
  CALL MPFR_SET_ZERO(TOL, TOL%TAG)
  IF (S .LT. C) THEN
     INFO = 0
  ELSE ! rotate
     IF (I .EQ. 0) THEN
        CALL MLJAU2(A1, A2, A(Q,P), C, S, INFO)
        CALL MRTVT(N, V(1,P), V(1,Q), C, S, INFO)
        CALL MRTRT(N, A, LDA, P, Q, C, S, INFO)
        CALL MRTLT(N, A, LDA, P, Q, C, S, INFO)
     ELSE ! hyp
        CALL MLJAV2(A1, A2, A(Q,P), C, S, INFO)
        CALL MRTVH(N, V(1,P), V(1,Q), C, S, INFO)
        CALL MRTRH(N, A, LDA, P, Q, C, S, INFO)
        CALL MRTLH(N, A, LDA, P, Q, C, S, INFO)
     END IF
     CALL MPFR_SET_M(TOL, S)
     IF (INFO .LT. 0) THEN
        INFO = -4
        RETURN
     END IF
     IF (IAND(INFO, 4) .NE. 0) THEN
        I = 0
     ELSE ! transf
        I = 2
     END IF
     CALL MPFR_SET_M(A(P,P), A1)
     CALL MPFR_SET_M(A(Q,Q), A2)
     IF ((I .EQ. 2) .AND. (IAND(INFO, 2) .EQ. 0)) CALL MPFR_SET_ZERO(A(Q,P), A(Q,P)%TAG)
     INFO = I
  END IF
  CALL MPFR_CLEAR_M(S)
  CALL MPFR_CLEAR_M(C)
  CALL MPFR_CLEAR_M(A2)
  CALL MPFR_CLEAR_M(A1)
END SUBROUTINE MTRANA
