PURE SUBROUTINE QCLEAR(N, A)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(KIND=REAL128), PARAMETER :: ZERO = 0.0_REAL128
  INTEGER, INTENT(IN) :: N
  REAL(KIND=REAL128), INTENT(OUT) :: A(N)
  INTEGER :: I
  DO I = 1, N
     A(I) = ZERO
  END DO
END SUBROUTINE QCLEAR
