PURE FUNCTION QDETM1(CS1, SN1, E)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
  IMPLICIT NONE
  REAL(REAL128), PARAMETER :: MONE = -1.0_REAL128
  REAL(REAL128), INTENT(IN) :: CS1, SN1, E
  REAL(REAL128) :: QDETM1
  QDETM1 = IEEE_FMA(CS1, CS1, IEEE_FMA(SN1, SN1, MONE)) / E
END FUNCTION QDETM1
