PURE FUNCTION QDETM1(CS1, SN1)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
  IMPLICIT NONE
  REAL(KIND=REAL128), PARAMETER :: MONE = -1.0_REAL128
  REAL(KIND=REAL128), INTENT(IN) :: CS1, SN1
  REAL(KIND=REAL128) :: QDETM1
  QDETM1 = IEEE_FMA(CS1, CS1, IEEE_FMA(SN1, SN1, MONE))
END FUNCTION QDETM1
