! C = A * B
PURE SUBROUTINE QMMMSQ(N, A, LDA, B, LDB, C, LDC)
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: N, LDA, LDB, LDC
  REAL(KIND=K), INTENT(IN) :: A(LDA,N), B(LDB,N)
  REAL(KIND=K), INTENT(OUT) :: C(LDC,N)
  INTEGER :: I, J, L
  DO J = 1, N
     DO I = 1, N
        C(I,J) = ZERO
     END DO
  END DO
  DO J = 1, N
     DO L = 1, N
        DO I = 1, N
           C(I,J) = IEEE_FMA(A(I,L), B(L,J), C(I,J))
        END DO
     END DO
  END DO
END SUBROUTINE QMMMSQ
