! Computed, eXact, Epsilon
PURE FUNCTION QRE(C, X, E)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(REAL128), PARAMETER :: ZERO = 0.0_REAL128
  REAL(REAL128), INTENT(IN) :: C, X, E
  REAL(REAL128) :: QRE
  REAL(REAL128) :: QAE
  QAE = C - X
  IF ((QAE .EQ. ZERO) .AND. ((X .EQ. ZERO) .OR. (E .EQ. ZERO))) THEN
     QRE = ZERO
  ELSE ! the general case
     QRE = QAE / (X * E)
  END IF
END FUNCTION QRE
