#ifdef _OPENMP
SUBROUTINE SCNRMF(M, N, G, LDG, SV, IX, INFO)
#else
PURE SUBROUTINE SCNRMF(M, N, G, LDG, SV, IX, INFO)
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE RECURSIVE FUNCTION SNRMF(M, X)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL32), INTENT(IN) :: X(M)
       REAL(KIND=REAL32) :: SNRMF
     END FUNCTION SNRMF
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M, N, LDG, IX(N)
  REAL(KIND=K), INTENT(IN) :: G(LDG,N)
  REAL(KIND=K), INTENT(OUT) :: SV(N)
  INTEGER, INTENT(OUT) :: INFO
  INTEGER :: J, L
#define NRMF SNRMF
#include "gcnrmf.f90"
END SUBROUTINE SCNRMF
