PURE FUNCTION SFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION C_FMA(X, Y, Z) BIND(C,NAME='fmaf')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
       REAL(KIND=c_float), INTENT(IN), VALUE :: X, Y, Z
       REAL(KIND=c_float) :: C_FMA
     END FUNCTION C_FMA
  END INTERFACE
  REAL(KIND=REAL32), INTENT(IN) :: A, B, C
  REAL(KIND=REAL32) :: SFMA
  SFMA = C_FMA(A, B, C)
END FUNCTION SFMA
