#ifdef _OPENMP
SUBROUTINE SINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
#else
PURE SUBROUTINE SINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE RECURSIVE FUNCTION SNRMF(M, X)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL32), INTENT(IN) :: X(M)
       REAL(KIND=REAL32) :: SNRMF
     END FUNCTION SNRMF
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: M, N, LDG, LDV
  REAL(KIND=K), INTENT(IN) :: G(LDG,N)
  REAL(KIND=K), INTENT(OUT) :: V(LDV,N), SV(N)
  INTEGER, INTENT(OUT) :: IX(N)
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER :: I, J
#define NRMF SNRMF
#include "ginisx.f90"
END SUBROUTINE SINISX
