PURE SUBROUTINE SINISX(M, N, G, LDG, V, LDV, SV, IX, GX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: M, N, LDG, LDV
  REAL(KIND=K), INTENT(IN) :: G(LDG,N)
  REAL(KIND=K), INTENT(OUT) :: V(LDV,N), SV(N), GX
  INTEGER, INTENT(OUT) :: IX(N), INFO
  REAL(KIND=K) :: W
  INTEGER :: I, J
#include "ginisx.f90"
END SUBROUTINE SINISX
