!  IN: GS = max sweeps, IX(1) = trace unit, INFO
! OUT: GS: backscale SV by 2**-GS, INFO: #sweeps
SUBROUTINE SJSVDP(M, N, G, LDG, V, LDV, JPOS, SV, GS, IX, WRK, RWRK, TBL, ORD, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64, REAL32
  IMPLICIT NONE
  INTERFACE
#ifdef _OPENMP
     SUBROUTINE SINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
#else
     PURE SUBROUTINE SINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDV
       REAL(KIND=REAL32), INTENT(IN) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: V(LDV,N), SV(N)
       INTEGER, INTENT(OUT) :: IX(N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SINISX
  END INTERFACE
  INTERFACE
#ifdef _OPENMP
     SUBROUTINE SSCALG(M, N, G, LDG, GX, GS, INFO)
#else
     PURE SUBROUTINE SSCALG(M, N, G, LDG, GX, GS, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N), GX
       INTEGER, INTENT(INOUT) :: GS, INFO
     END SUBROUTINE SSCALG
  END INTERFACE
  INTERFACE
#ifdef _OPENMP
     SUBROUTINE SPRCYC(M, N, G, LDG, JPOS, SV, IX, WRK, RWRK, INFO)
#else
     PURE SUBROUTINE SPRCYC(M, N, G, LDG, JPOS, SV, IX, WRK, RWRK, INFO)
#endif
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, JPOS
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N)
       REAL(KIND=REAL32), INTENT(OUT) :: SV(N), WRK(M,N), RWRK(N)
       INTEGER, INTENT(INOUT) :: IX(N), INFO
     END SUBROUTINE SPRCYC
  END INTERFACE
  INTERFACE
     SUBROUTINE STRNSP(M, N, G, LDG, V, LDV, SV, GX, P, Q, TOL, IX, WRK, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDV, P, Q, IX(N)
       REAL(KIND=REAL32), INTENT(INOUT) :: G(LDG,N), V(LDV,N), SV(N), GX, TOL
       REAL(KIND=REAL32), INTENT(OUT) :: WRK(M,N)
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE STRNSP
  END INTERFACE
  INTERFACE
     SUBROUTINE STRACK(N, SV, GX, GS, SWP, NTR, U)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, GS, SWP, NTR, U
       REAL(KIND=REAL32), INTENT(IN) :: SV(N), GX
     END SUBROUTINE STRACK
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K, EPS = EPSILON(EPS) / 2
  INTEGER, INTENT(IN) :: M, N, LDG, LDV, JPOS, TBL(2,*)
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N)
  REAL(KIND=K), INTENT(OUT) :: V(LDV,N), SV(N), WRK(M,N), RWRK(N)
  INTEGER, INTENT(INOUT) :: GS, IX(N), ORD(2,*), INFO
  REAL(KIND=K) :: GX, TOL, X, Y
  INTEGER(KIND=INT64) :: TT
  INTEGER :: L, O, P, Q, R, S, T, U, W, ST, TP, TS
#define GINISX SINISX
#define GSCALG SSCALG
#define GPRCYC SPRCYC
#define GTRNSP STRNSP
#define GTRACK STRACK
#define GSQRT SQRT
#include "gjsvdp.f90"
END SUBROUTINE SJSVDP
