SUBROUTINE SLJAV2(A11, A22, A21, CH, SH, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#ifdef USE_IEEE_INTRINSIC
#define SFMA IEEE_FMA
#else
  INTERFACE
     PURE FUNCTION SFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: A, B, C
       REAL(KIND=REAL32) :: SFMA
     END FUNCTION SFMA
  END INTERFACE
#endif
  INTERFACE
     FUNCTION PVN_SLJV2(A11, A22, A21, CH, SH, TH, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_float
       REAL(KIND=c_float), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_float), INTENT(OUT) :: CH, SH, TH
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_SLJV2
     END FUNCTION PVN_SLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22
  REAL(KIND=K), INTENT(IN) :: A21
  REAL(KIND=K), INTENT(OUT) :: CH, SH
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: A, TH
  INTEGER(KIND=c_int) :: ES, RT
#define GFMA SFMA
#define LJV2 PVN_SLJV2
#include "gljav2.f90"
END SUBROUTINE SLJAV2
