SUBROUTINE SLJTU2(A11, A22, A21, CS, TN, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_SLJEU2(A11, A22, A21, CS, TN, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_float
       REAL(KIND=c_float), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_float), INTENT(OUT) :: CS, TN, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_SLJEU2
     END FUNCTION PVN_SLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21
  REAL(KIND=K), INTENT(OUT) :: CS, TN
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
#define LJEU2 PVN_SLJEU2
#include "gljtu2.f90"
END SUBROUTINE SLJTU2
