SUBROUTINE SLJU2(A11, A22, A21, CS, SN, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32, ONE = 1.0_REAL32
  REAL(KIND=REAL32), INTENT(IN) :: A11, A22, A21
  REAL(KIND=REAL32), INTENT(OUT) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_SLJEU2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_SLJEU2(A11, A22, A21, CS, SN, ES))
  INCLUDE 'glju2.f90'
END SUBROUTINE SLJU2
