SUBROUTINE SLJV2(A11, A22, A21, CH, SH, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  REAL(KIND=REAL32), PARAMETER :: ZERO = 0.0_REAL32, ONE = 1.0_REAL32
  REAL(KIND=REAL32), PARAMETER :: CUTTH = 4.0_REAL32 / 5.0_REAL32
  REAL(KIND=REAL32), PARAMETER :: CUTCH = 5.0_REAL32 / 3.0_REAL32
  REAL(KIND=REAL32), PARAMETER :: CUTSH = 4.0_REAL32 / 3.0_REAL32
  REAL(KIND=REAL32), INTENT(IN) :: A11, A22, A21
  REAL(KIND=REAL32), INTENT(OUT) :: CH, SH
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=REAL32) :: A
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_SLJV2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_SLJV2(A11, A22, A21, CH, SH, ES))
  INCLUDE 'gljv2.f90'
END SUBROUTINE SLJV2
