PURE FUNCTION SNRMOA(N, A, LDA, AS)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: KK = REAL64
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=KK), PARAMETER :: ZERO = 0.0_KK, SQRT2 = SQRT(2.0_KK)
  INTEGER, INTENT(IN) :: N, LDA, AS
  REAL(KIND=K), INTENT(IN) :: A(LDA,N)
  REAL(KIND=KK) :: SNRMOA
  INTEGER :: I, J, L
  SNRMOA = ZERO
  IF (N .LE. 1) RETURN
  L = -AS
  DO J = 1, N-1
     DO I = J+1, N
        SNRMOA = CR_HYPOT(SNRMOA, SCALE(REAL(A(I,J), KK), L))
     END DO
  END DO
  SNRMOA = SNRMOA * SQRT2
END FUNCTION SNRMOA
