PURE RECURSIVE FUNCTION SNRMF(M, X) RESULT(F)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, MZERO = -0.0_K
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: F
  INTEGER :: I
  IF (M .LT. 0) THEN
     F = MZERO
  ELSE IF (M .EQ. 0) THEN
     F = ZERO
  ELSE IF (M .EQ. 1) THEN
     F = ABS(X(1))
  ELSE IF (M .EQ. 2) THEN
     F = CR_HYPOT(X(1), X(2))
  ELSE ! M > 2
     I = ISHFT(M, -1) + IAND(M, 1)
     F = CR_HYPOT(SNRMF(I, X), SNRMF(M-I, X(I+1)))
  END IF
END FUNCTION SNRMF
