PURE FUNCTION SNRMF(M, X)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: SNRMF
  INTEGER :: I
  SNRMF = ZERO
  IF (M .LE. 0) RETURN
  SNRMF = ABS(X(1))
  DO I = 2, M
     SNRMF = CR_HYPOT(SNRMF, X(I))
  END DO
END FUNCTION SNRMF
