PURE SUBROUTINE SNSORT(N, JPOS, SV, IX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, JPOS
  REAL(KIND=K), INTENT(INOUT) :: SV(N)
  INTEGER, INTENT(INOUT) :: IX(N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: X
  INTEGER :: I, J, L, M
#include "gnsort.f90"
END SUBROUTINE SNSORT
