FUNCTION SRSAFE(U)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(KIND=c_float) :: SRSAFE
  REAL(KIND=c_float) :: RMIN, RMAX, R
  RMIN = TINY(R)
  R = HUGE(R)
  RMAX = SCALE(R, -2)
  DO WHILE ((.NOT. (R .GE. RMIN)) .OR. (.NOT. (R .LE. RMAX)))
     READ (U) R
  END DO
  SRSAFE = R
END FUNCTION SRSAFE
