FUNCTION SRSAFE(U)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(KIND=c_float) :: SRSAFE
  REAL(KIND=c_float) :: RMIN, RMAX, R, A
  RMIN = TINY(A)
  A = HUGE(A)
  RMAX = SCALE(A, -2)
  DO WHILE ((.NOT. (A .GE. RMIN)) .OR. (.NOT. (A .LE. RMAX)))
     READ (U) R
     A = ABS(R)
  END DO
  SRSAFE = R
END FUNCTION SRSAFE
