PURE SUBROUTINE SRTLH(N, A, LDA, AX, P, Q, CH, SH, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N), AX
  REAL(KIND=K), INTENT(IN) :: CH, SH
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: XX, YY
  INTEGER :: J
#define GFMA SFMA
#include "grtlh.f90"
END SUBROUTINE SRTLH
