PURE SUBROUTINE SRTLT(N, A, LDA, AX, P, Q, CS, SN, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION SFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: A, B, C
       REAL(KIND=REAL32) :: SFMA
     END FUNCTION SFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N), AX
  REAL(KIND=K), INTENT(IN) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: XX, YY
  INTEGER :: J
#define GFMA SFMA
#include "grtlt.f90"
END SUBROUTINE SRTLT
