PURE SUBROUTINE SRTT(M, X, Y, CS, TN, GX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#ifdef USE_IEEE_INTRINSIC
#define SFMA IEEE_FMA
#else
  INTERFACE
     PURE FUNCTION SFMA(A, B, C) BIND(C,NAME='fmaf')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN), VALUE :: A, B, C
       REAL(KIND=REAL32) :: SFMA
     END FUNCTION SFMA
  END INTERFACE
#endif
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(INOUT) :: X(M), Y(M), GX
  REAL(KIND=K), INTENT(IN) :: CS, TN
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: XX, YY, NT
  INTEGER :: I
#define GFMA SFMA
#include "grtt.f90"
END SUBROUTINE SRTT
