PURE SUBROUTINE SSWPC(N, A, LDA, P, Q, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: T
  INTEGER :: I
  INCLUDE 'gswpc.f90'
END SUBROUTINE SSWPC
