PROGRAM STEST
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_float
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(c_float), PARAMETER :: HALF = 0.5_c_float
  REAL(c_float), TARGET :: A, B, C, RT1, RT2, CS1, SN1
  REAL(REAL128), TARGET :: QA, QB, QC, QRT1, QRT2, QCS1, QSN1
  REAL(REAL128) :: D, REC, RES
  INTEGER :: U
  EXTERNAL :: SJIEV2, SLAEV2, QJAEV2
  U = ORFILE()
  A = SRSAFE(U)
  B = SRSAFE(U)
  C = SRSAFE(U)
  CLOSE(U)
  WRITE (*,9,ADVANCE='NO') 'A(1,:):', A
  WRITE (*,9) ',', B
  WRITE (*,9,ADVANCE='NO') 'A(2,:):', B
  WRITE (*,9) ',', C
  U = 0
  CALL SJIEV2(A, B, C, RT1, RT2, CS1, SN1, U)
  IF (U .NE. 0) WRITE (*,'(A,I2)') 'SJIEV2=', U
  WRITE (*,9) ' CS1=', CS1
  WRITE (*,9) ' SN1=', SN1
  WRITE (*,9) ' RT1=', RT1
  WRITE (*,9) ' RT2=', RT2
  REC = CS1
  RES = SN1
  D = QDETM1(REC, RES)
  WRITE (*,9) 'QDET=', D
  QA = A
  QB = B
  QC = C
  CALL QJAEV2(QA, QB, QC, QRT1, QRT2, QCS1, QSN1)
  WRITE (*,9) 'QCS1=', QCS1
  WRITE (*,9) 'QSN1=', QSN1
  WRITE (*,9) 'QRT1=', QRT1
  WRITE (*,9) 'QRT2=', QRT2
  D = EPSILON(HALF) * HALF
  REC = CS1
  RES = QCS1
  REC = QRE(REC, RES, D)
  WRITE (*,9) 'QREC=', REC
  REC = SN1
  RES = QSN1
  RES = QRE(REC, RES, D)
  WRITE (*,9) 'QRES=', RES
  CALL SLAEV2(A, B, C, RT1, RT2, CS1, SN1)
  WRITE (*,9) 'LCS1=', CS1
  WRITE (*,9) 'LSN1=', SN1
  WRITE (*,9) 'LRT1=', RT1
  WRITE (*,9) 'LRT2=', RT2
  REC = CS1
  RES = SN1
  D = QDETM1(REC, RES)
  WRITE (*,9) 'QDET=', D
9 FORMAT(A,ES16.9E2)
CONTAINS
#include "orfile.F90"
#include "srsafe.F90"
#include "qdetm1.F90"
#include "qre.F90"
END PROGRAM STEST
