SUBROUTINE STRACK(N, SV, GX, GS, SWP, NTR)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, GS, SWP, NTR
  REAL(KIND=K), INTENT(IN) :: SV(N), GX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,I11,I7,ES16.9E2)') SWP, NTR, GS, GX
  I = -GS
  DO J = 1, N
     WRITE (ERROR_UNIT,'(I3,ES16.9E2)') J, SCALE(REAL(SV(J), REAL64), I)
  END DO
END SUBROUTINE STRACK
