SUBROUTINE STRACK(N, SV, GX, GS, SWP, NTR, U)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32, REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL32
  INTEGER, INTENT(IN) :: N, GS, SWP, NTR, U
  REAL(KIND=K), INTENT(IN) :: SV(N), GX
  INTEGER :: I, J
  WRITE (U,'(I10,A,I11,A,I6,A,ES16.9E2)') SWP, ',', ABS(NTR), ',', GS, ',', GX
  FLUSH(U)
  IF ((NTR .GT. 0) .AND. (N .LT. 1000)) THEN
     I = -GS
     DO J = 1, N
        WRITE (U,'(I3,A,ES16.9E2)') J, ',', SCALE(REAL(SV(J), REAL64), I)
        FLUSH(U)
     END DO
  END IF
END SUBROUTINE STRACK
