! IN: INFO & 1: hyp
!     INFO & 2: SLOW
!OUT: INFO = 0: notransf due to tol
!     INFO = 1: notransf due to identity transf
!     INFO = 2: transf
!     INFO = 3: transf, big th
SUBROUTINE STRNSP(M, N, G, LDG, V, LDV, SV, GX, P, Q, TOL, IX, WRK, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, REAL32
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
  INTERFACE
     PURE FUNCTION SNRMF(M, X)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL32), INTENT(IN) :: X(M)
       REAL(KIND=REAL32) :: SNRMF
     END FUNCTION SNRMF
  END INTERFACE
  INTERFACE
     FUNCTION SSDP(M, X, Y, MX, MY, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       INTEGER, INTENT(INOUT) :: INFO
       REAL(KIND=REAL32), INTENT(IN) :: X(M), Y(M), MX, MY
       REAL(KIND=REAL32) :: SSDP
     END FUNCTION SSDP
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SGRAM(PNF, QNF, QPS, APP, AQQ, AQP, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(IN) :: PNF, QNF, QPS
       REAL(KIND=REAL32), INTENT(OUT) :: APP, AQQ, AQP
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE SGRAM
  END INTERFACE
  INTERFACE
     SUBROUTINE SLJTU2(A11, A22, A21, CS, TN, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(INOUT) :: A11, A22, A21
       REAL(KIND=REAL32), INTENT(OUT) :: CS, TN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SLJTU2
  END INTERFACE
  INTERFACE
     SUBROUTINE SLJTV2(A11, A22, A21, CH, TH, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       REAL(KIND=REAL32), INTENT(INOUT) :: A11, A22, A21, CH
       REAL(KIND=REAL32), INTENT(OUT) :: TH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SLJTV2
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SRTT(M, X, Y, CS, TN, GX, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL32), INTENT(INOUT) :: X(M), Y(M), GX
       REAL(KIND=REAL32), INTENT(IN) :: CS, TN
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SRTT
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE SRTH(M, X, Y, CH, TH, GX, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL32
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       REAL(KIND=REAL32), INTENT(INOUT) :: X(M), Y(M), GX
       REAL(KIND=REAL32), INTENT(IN) :: CH, TH
       INTEGER, INTENT(INOUT) :: INFO
     END SUBROUTINE SRTH
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL32
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: M, N, LDG, LDV, P, Q, IX(N)
  REAL(KIND=K), INTENT(INOUT) :: G(LDG,N), V(LDV,N), SV(N), GX, TOL
  REAL(KIND=K), INTENT(OUT) :: WRK(M,N)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: QPS, APP, AQQ, AQP, C, S, T
  INTEGER :: I, J, L, O, E
#define GNRMF SNRMF
#define GSDP SSDP
#define GGRAM SGRAM
#define GLJTU2 SLJTU2
#define GLJTV2 SLJTV2
#define GRTT SRTT
#define GRTH SRTH
#define GSQRT SQRT
#define GFMA SFMA
#include "gtrnsp.f90"
END SUBROUTINE STRNSP
