PURE FUNCTION WFMA(A, B, C)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  COMPLEX(KIND=c_long_double), INTENT(IN) :: A, B, C
  COMPLEX(KIND=c_long_double) :: WFMA
#else
  COMPLEX(KIND=REAL128), INTENT(IN) :: A, B, C
  COMPLEX(KIND=REAL128) :: WFMA
#endif
  WFMA = A * B + C
END FUNCTION WFMA
