PURE FUNCTION WFMA(A, B, C)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_WFMA(DR, DI, AR, AI, BR, BI, CR, CI)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       REAL(KIND=c_long_double), INTENT(OUT) :: DR, DI
       REAL(KIND=c_long_double), INTENT(IN) :: AR, AI, BR, BI, CR, CI
     END SUBROUTINE PVN_WFMA
  END INTERFACE
  COMPLEX(KIND=c_long_double), INTENT(IN) :: A, B, C
  COMPLEX(KIND=c_long_double) :: WFMA
  REAL(KIND=c_long_double) :: DR, DI
  CALL PVN_WFMA(DR, DI, REAL(A), AIMAG(A), REAL(B), AIMAG(B), REAL(C), AIMAG(C))
  WFMA = CMPLX(DR, DI, c_long_double)
END FUNCTION WFMA
