SUBROUTINE WGRAM(PNF, QNF, QPS, APP, AQQ, AQPR, AQPI, INFO)
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = 10
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  REAL(KIND=K), INTENT(IN) :: PNF, QNF
  COMPLEX(KIND=K), INTENT(IN) :: QPS
  REAL(KIND=K), INTENT(OUT) :: APP, AQQ, AQPR, AQPI
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: FP, FQ, F1, F2
  INTEGER :: EP, EQ, E1, E2
  INCLUDE 'hgram.f90'
END SUBROUTINE WGRAM
