SUBROUTINE WLJTV2(A11, A22, A21R, A21I, CH, THR, THI, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
#else
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
#ifdef __GFORTRAN__
  INTERFACE
     FUNCTION PVN_WLJV2(A11, A22, A21R, A21I, CH, THR, THI, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_long_double), INTENT(OUT) :: CH, THR, THI
       REAL(KIND=c_long_double), INTENT(INOUT) :: TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_WLJV2
     END FUNCTION PVN_WLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTERFACE
     FUNCTION PVN_YLJV2(A11, A22, A21R, A21I, CH, THR, THI, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=REAL128), INTENT(OUT) :: CH, THR, THI
       REAL(KIND=REAL128), INTENT(INOUT) :: TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_YLJV2
     END FUNCTION PVN_YLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22, A21R, A21I, CH
  REAL(KIND=K), INTENT(OUT) :: THR, THI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
  LOGICAL :: WD
#define GFMA XFMA
#ifdef __GFORTRAN__
#define LJV2 PVN_WLJV2
#else
#define LJV2 PVN_YLJV2
#endif
#include "hljtv2.f90"
END SUBROUTINE WLJTV2
