SUBROUTINE WLJTU2(A11, A22, A21R, A21I, CS, TNR, TNI, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
#else
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION XFMA(A, B, C)
#ifdef __GFORTRAN__
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
       IMPLICIT NONE
#ifdef __GFORTRAN__
       REAL(KIND=c_long_double), INTENT(IN) :: A, B, C
       REAL(KIND=c_long_double) :: XFMA
#else
       REAL(KIND=REAL128), INTENT(IN) :: A, B, C
       REAL(KIND=REAL128) :: XFMA
#endif
     END FUNCTION XFMA
  END INTERFACE
#ifdef __GFORTRAN__
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotl')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       REAL(KIND=c_long_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_long_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTERFACE
     FUNCTION PVN_WLJEU2(A11, A22, A21R, A21I, CS, TNR, TNI, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_long_double), INTENT(OUT) :: CS, TNR, TNI, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_WLJEU2
     END FUNCTION PVN_WLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
#define CR_HYPOT HYPOT
  INTERFACE
     FUNCTION PVN_YLJEU2(A11, A22, A21R, A21I, CS, TNR, TNI, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=REAL128), INTENT(OUT) :: CS, TNR, TNI, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_YLJEU2
     END FUNCTION PVN_YLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22, A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CS, TNR, TNI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
  LOGICAL :: WD
#define GFMA XFMA
#ifdef __GFORTRAN__
#define LJEU2 PVN_WLJEU2
#else
#define LJEU2 PVN_YLJEU2
#endif
#include "hljtu2.f90"
END SUBROUTINE WLJTU2
