SUBROUTINE WLJU2(A11, A22, A21R, A21I, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_WLJEU2(A11, A22, A21R, A21I, CS, SNR, SNI, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_long_double), INTENT(OUT) :: CS, SNR, SNI
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_WLJEU2
     END FUNCTION PVN_WLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES, RT
#define LJU2 PVN_WLJEU2
#include "hlju2.f90"
END SUBROUTINE WLJU2
