SUBROUTINE WLJU2(A11, A22, A21R, A21I, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_LJEU2(A11, A22, A21R, A21I, CS, SNR, SNI, ES) BIND(C,NAME='pvn_wljeu2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_long_double), INTENT(OUT) :: CS, SNR, SNI
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_LJEU2
     END FUNCTION PVN_LJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = 10
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INCLUDE 'hlju2.f90'
END SUBROUTINE WLJU2
