! C += A * B
#ifdef _OPENMP
SUBROUTINE WMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#else
PURE SUBROUTINE WMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#endif
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTERFACE
     PURE FUNCTION WFMA(A, B, C)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       COMPLEX(KIND=c_long_double), INTENT(IN) :: A, B, C
       COMPLEX(KIND=c_long_double) :: WFMA
     END FUNCTION WFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTERFACE
     PURE FUNCTION WFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       COMPLEX(KIND=REAL128), INTENT(IN) :: A, B, C
       COMPLEX(KIND=REAL128) :: WFMA
     END FUNCTION WFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  INTEGER, INTENT(IN) :: M, N, LDA, LDB, LDC
  COMPLEX(KIND=K), INTENT(IN) :: A(LDA,M), B(LDB,N)
  COMPLEX(KIND=K), INTENT(INOUT) :: C(LDC,N)
  INTEGER :: I, J, L
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I,J,L) SHARED(A,B,C,M,N)
  DO J = 1, N
     DO L = 1, M
        DO I = 1, N
           C(I,J) = WFMA(A(I,L), B(L,J), C(I,J))
        END DO
     END DO
  END DO
  !$OMP END PARALLEL DO
END SUBROUTINE WMMMSQ
