PURE FUNCTION WNRMF(M, X)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypotl')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       REAL(KIND=c_long_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_long_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
#define CR_HYPOT HYPOT
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: WNRMF
  INTEGER :: I
  WNRMF = ZERO
  IF (M .LE. 0) RETURN
  WNRMF = CR_HYPOT(REAL(X(1)), AIMAG(X(1)))
  DO I = 2, M
     WNRMF = CR_HYPOT(WNRMF, CR_HYPOT(REAL(X(I)), AIMAG(X(I))))
  END DO
END FUNCTION WNRMF
