SUBROUTINE WRN(M, N, A)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N
#ifdef __GFORTRAN__
  REAL(KIND=c_long_double), INTENT(OUT) :: A(2*M,N)
#else
  REAL(KIND=REAL128), INTENT(OUT) :: A(2*M,N)
#endif
  CALL RANDOM_NUMBER(A)
END SUBROUTINE WRN
