PURE SUBROUTINE WRTVT(N, X, Y, CS, SNR, SNI, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTERFACE
     PURE FUNCTION WFMA(A, B, C)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       COMPLEX(KIND=c_long_double), INTENT(IN) :: A, B, C
       COMPLEX(KIND=c_long_double) :: WFMA
     END FUNCTION WFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTERFACE
     PURE FUNCTION WFMA(A, B, C)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       COMPLEX(KIND=REAL128), INTENT(IN) :: A, B, C
       COMPLEX(KIND=REAL128) :: WFMA
     END FUNCTION WFMA
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  INTEGER, INTENT(IN) :: N
  COMPLEX(KIND=K), INTENT(INOUT) :: X(N), Y(N)
  REAL(KIND=K), INTENT(IN) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: SN, HS, XX, YY
  INTEGER :: I
#define HFMA WFMA
#include "hrtvt.f90"
END SUBROUTINE WRTVT
