PURE SUBROUTINE WRTVT(M, X, Y, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = c_long_double
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(INOUT) :: X(M), Y(M)
  REAL(KIND=K), INTENT(IN) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: SN, HS, XX, YY
  INTEGER :: I
  INCLUDE 'hrtvt.f90'
END SUBROUTINE WRTVT
