FUNCTION WSDP(M, X, Y, MX, MY, INFO)
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = 10
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(IN) :: X(M), Y(M)
  REAL(KIND=K), INTENT(IN) :: MX, MY
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=K) :: WSDP
  INTEGER :: I
  INFO = 0
  WSDP = ZERO
  IF (.NOT. (MY .GT. ZERO)) INFO = -5
  IF (.NOT. (MX .GT. ZERO)) INFO = -4
  IF (M .LT. 0) INFO = -1
  IF (INFO .NE. 0) RETURN
  DO I = 1, M
     WSDP = WSDP + (CONJG(X(I)) / MX) * (Y(I) / MY)
  END DO
END FUNCTION WSDP
