PURE SUBROUTINE WSWPR(N, A, LDA, P, Q, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTEGER, PARAMETER :: K = REAL128
#endif
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: A(LDA,N)
  INTEGER, INTENT(OUT) :: INFO
  COMPLEX(KIND=K) :: T
  INTEGER :: J
#include "hswpr.f90"
END SUBROUTINE WSWPR
