PURE SUBROUTINE WSWPXD(N, A, LDA, V, LDV, B, E, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE WSWPC(N, A, LDA, P, Q, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       COMPLEX(KIND=c_long_double), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE WSWPC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE WSWPR(N, A, LDA, P, Q, INFO)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       COMPLEX(KIND=c_long_double), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE WSWPR
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: N, LDA, LDV, B, E
  COMPLEX(KIND=K), INTENT(INOUT) :: A(LDA,N), V(LDV,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: X, T
  INTEGER :: J
#define SWPC WSWPC
#define SWPR WSWPR
#include "hswpxd.f90"
END SUBROUTINE WSWPXD
