SUBROUTINE WTRACE(N, A, LDA, AX, AS, SWP, NTR)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = c_long_double
  INTEGER, INTENT(IN) :: N, LDA, AS, SWP, NTR
  COMPLEX(KIND=K), INTENT(IN) :: A(LDA,N)
  REAL(KIND=K), INTENT(IN) :: AX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,A,I11,A,I6,A,ES30.21E4)') SWP, ',', NTR, ',', AS, ',', AX
  FLUSH(ERROR_UNIT)
  IF (N .LT. 1000) THEN
     I = -AS
     DO J = 1, N
        WRITE (ERROR_UNIT,'(I3,A,ES30.21E4)') J, ',', SCALE(REAL(REAL(A(J,J)), REAL128), I)
        FLUSH(ERROR_UNIT)
     END DO
  END IF
END SUBROUTINE WTRACE
