PURE SUBROUTINE XGRAM(PNF, QNF, QPS, APP, AQQ, AQP, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = c_long_double
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  REAL(KIND=K), INTENT(IN) :: PNF, QNF, QPS
  REAL(KIND=K), INTENT(OUT) :: APP, AQQ, AQP
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: FP, FQ, F1, F2
  INTEGER :: EP, EQ, E1, E2
  INCLUDE 'ggram.f90'
END SUBROUTINE XGRAM
