SUBROUTINE XLJAU2(A11, A22, A21, CS, SN, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
#else
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTERFACE
     FUNCTION PVN_XLJEV2(A11, A22, A21, CS, SN, L1, L2, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_long_double), INTENT(OUT) :: CS, SN, L1, L2
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_XLJEV2
     END FUNCTION PVN_XLJEV2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTERFACE
     FUNCTION PVN_QLJEV2(A11, A22, A21, CS, SN, L1, L2, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: A11, A22, A21
       REAL(KIND=REAL128), INTENT(OUT) :: CS, SN, L1, L2
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_QLJEV2
     END FUNCTION PVN_QLJEV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22
  REAL(KIND=K), INTENT(IN) :: A21
  REAL(KIND=K), INTENT(OUT) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: L1, L2
  INTEGER :: S
  INTEGER(KIND=c_int) :: ES, RT
#ifdef __GFORTRAN__
#define LJU2 PVN_XLJEV2
#else
#define LJU2 PVN_QLJEV2
#endif
#include "gljau2.f90"
END SUBROUTINE XLJAU2
