SUBROUTINE XLJTU2(A11, A22, A21, CS, TN, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
#else
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTERFACE
     FUNCTION PVN_XLJEU2(A11, A22, A21, CS, TN, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_long_double), INTENT(OUT) :: CS, TN, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_XLJEU2
     END FUNCTION PVN_XLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTERFACE
     FUNCTION PVN_QLJEU2(A11, A22, A21, CS, TN, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: A11, A22, A21
       REAL(KIND=REAL128), INTENT(OUT) :: CS, TN, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_QLJEU2
     END FUNCTION PVN_QLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22
  REAL(KIND=K), INTENT(INOUT) :: A21
  REAL(KIND=K), INTENT(OUT) :: CS, TN
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
#ifdef __GFORTRAN__
#define LJEU2 PVN_XLJEU2
#else
#define LJEU2 PVN_QLJEU2
#endif
#include "gljtu2.f90"
END SUBROUTINE XLJTU2
