SUBROUTINE XLJTV2(A11, A22, A21, CH, TH, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
#else
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
#ifdef __GFORTRAN__
  INTERFACE
     FUNCTION PVN_XLJV2(A11, A22, A21, CH, TH, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_long_double), INTENT(OUT) :: CH, TH
       REAL(KIND=c_long_double), INTENT(INOUT) :: TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_XLJV2
     END FUNCTION PVN_XLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTERFACE
     FUNCTION PVN_QLJV2(A11, A22, A21, CH, TH, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN) :: A11, A22, A21
       REAL(KIND=REAL128), INTENT(OUT) :: CH, TH
       REAL(KIND=REAL128), INTENT(INOUT) :: TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_QLJV2
     END FUNCTION PVN_QLJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(INOUT) :: A11, A22, A21, CH
  REAL(KIND=K), INTENT(OUT) :: TH
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
  LOGICAL :: WD
#define GFMA XFMA
#ifdef __GFORTRAN__
#define LJV2 PVN_XLJV2
#else
#define LJV2 PVN_QLJV2
#endif
#include "gljtv2.f90"
END SUBROUTINE XLJTV2
