SUBROUTINE XLJU2(A11, A22, A21, CS, SN, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  IMPLICIT NONE
  REAL(KIND=10), INTENT(IN) :: A11, A22, A21
  REAL(KIND=10), INTENT(OUT) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_XLJEU2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_XLJEU2(A11, A22, A21, CS, SN, ES))
END SUBROUTINE XLJU2
