SUBROUTINE XLJU2(A11, A22, A21, CS, SN, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  IMPLICIT NONE
  REAL(KIND=10), PARAMETER :: ZERO = 0.0_10, ONE = 1.0_10
  REAL(KIND=10), INTENT(IN) :: A11, A22, A21
  REAL(KIND=10), INTENT(OUT) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_XLJEU2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_XLJEU2(A11, A22, A21, CS, SN, ES))
  IF (INFO .GE. 0) THEN
     INFO = IAND(INFO, 1)
     IF ((CS .EQ. ONE) .AND. (SN .EQ. ZERO)) INFO = IOR(INFO, 4)
  END IF
END SUBROUTINE XLJU2
