SUBROUTINE XLJU2(A11, A22, A21, CS, SN, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_XLJEU2(A11, A22, A21, CS, SN, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_long_double
       REAL(KIND=c_long_double), INTENT(IN) :: A11, A22, A21
       REAL(KIND=c_long_double), INTENT(OUT) :: CS, SN
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_XLJEU2
     END FUNCTION PVN_XLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = c_long_double
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21
  REAL(KIND=K), INTENT(OUT) :: CS, SN
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES, RT
#define LJU2 PVN_XLJEU2
#include "glju2.f90"
END SUBROUTINE XLJU2
