PURE FUNCTION XNRMOA(N, A, LDA, AS)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
#define HYPOTX HYPOT
  INTEGER, PARAMETER :: KK = REAL128
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=KK), PARAMETER :: ZERO = 0.0_KK, SQRT2 = SQRT(2.0_KK)
  INTEGER, INTENT(IN) :: N, LDA, AS
  REAL(KIND=K), INTENT(IN) :: A(LDA,N)
  REAL(KIND=KK) :: XNRMOA
  INTEGER :: I, J, L
  XNRMOA = ZERO
  IF (N .LE. 1) RETURN
  L = -AS
  DO J = 1, N-1
     DO I = J+1, N
        XNRMOA = HYPOTX(XNRMOA, SCALE(REAL(A(I,J), KK), L))
     END DO
  END DO
  XNRMOA = XNRMOA * SQRT2
END FUNCTION XNRMOA
