PURE FUNCTION XNRMF(M, X)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#include "cr.f90"
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: M
  REAL(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: XNRMF
  INTEGER :: I
  XNRMF = ZERO
  IF (M .LE. 0) RETURN
  XNRMF = ABS(X(1))
  DO I = 2, M
     XNRMF = CR_HYPOT(XNRMF, X(I))
  END DO
END FUNCTION XNRMF
