PURE SUBROUTINE XNSORT(N, JPOS, SV, IX, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTEGER, PARAMETER :: K = REAL128
#endif
  INTEGER, INTENT(IN) :: N, JPOS
  REAL(KIND=K), INTENT(INOUT) :: SV(N)
  INTEGER, INTENT(INOUT) :: IX(N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: X
  INTEGER :: I, J, L, M
#include "gnsort.f90"
END SUBROUTINE XNSORT
