FUNCTION XRSAFE(U)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(KIND=c_long_double) :: XRSAFE
  REAL(KIND=c_long_double) :: RMIN, RMAX, R
  RMIN = TINY(R)
  R = HUGE(R)
  RMAX = SCALE(R, -2)
  DO WHILE ((.NOT. (R .GE. RMIN)) .OR. (.NOT. (R .LE. RMAX)))
     READ (U) R
  END DO
  XRSAFE = R
END FUNCTION XRSAFE
