FUNCTION XRSAFE(U)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: U
  REAL(10) :: XRSAFE, RMIN, RMAX, R, A
  RMIN = TINY(A)
  A = HUGE(A)
  RMAX = SCALE(A, -2)
  DO WHILE ((.NOT. (A .GE. RMIN)) .OR. (.NOT. (A .LE. RMAX)))
     READ (U) R
     A = ABS(R)
  END DO
  XRSAFE = R
END FUNCTION XRSAFE
