PURE FUNCTION XSQRT(X)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
  INTERFACE
#ifdef __GFORTRAN__
     PURE FUNCTION C_SQRT(X) BIND(C,NAME='sqrtl')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
       REAL(KIND=c_long_double), INTENT(IN), VALUE :: X
       REAL(KIND=c_long_double) :: C_SQRT
     END FUNCTION C_SQRT
#else
     PURE FUNCTION C_SQRT(X) BIND(C,NAME='sqrtq')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
       REAL(KIND=REAL128), INTENT(IN), VALUE :: X
       REAL(KIND=REAL128) :: C_SQRT
     END FUNCTION C_SQRT
#endif
  END INTERFACE
#ifdef __GFORTRAN__
  REAL(KIND=c_long_double), INTENT(IN) :: X
  REAL(KIND=c_long_double) :: XSQRT
#else
  REAL(KIND=REAL128), INTENT(IN) :: X
  REAL(KIND=REAL128) :: XSQRT
#endif
  XSQRT = C_SQRT(X)
END FUNCTION XSQRT
