PURE SUBROUTINE XSWPXD(N, A, LDA, V, LDV, B, E, INFO)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE XSWPC(N, A, LDA, P, Q, INFO)
#ifdef __GFORTRAN__
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
#ifdef __GFORTRAN__
       REAL(KIND=c_long_double), INTENT(INOUT) :: A(LDA,N)
#else
       REAL(KIND=REAL128), INTENT(INOUT) :: A(LDA,N)
#endif
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XSWPC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE XSWPR(N, A, LDA, P, Q, INFO)
#ifdef __GFORTRAN__
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
#else
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
#endif
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
#ifdef __GFORTRAN__
       REAL(KIND=c_long_double), INTENT(INOUT) :: A(LDA,N)
#else
       REAL(KIND=REAL128), INTENT(INOUT) :: A(LDA,N)
#endif
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE XSWPR
  END INTERFACE
#ifdef __GFORTRAN__
  INTEGER, PARAMETER :: K = c_long_double
#else
  INTEGER, PARAMETER :: K = REAL128
#endif
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: N, LDA, LDV, B, E
  REAL(KIND=K), INTENT(INOUT) :: A(LDA,N), V(LDV,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: X, T
  INTEGER :: J
#define SWPC XSWPC
#define SWPR XSWPR
#include "gswpxd.f90"
END SUBROUTINE XSWPXD
