SUBROUTINE XTRACK(N, SV, GX, GS, SWP, NTR)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_long_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT, REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = c_long_double
  INTEGER, INTENT(IN) :: N, GS, SWP, NTR
  REAL(KIND=K), INTENT(IN) :: SV(N), GX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,A,I11,A,I6,A,ES30.21E4)') SWP, ',', NTR, ',', GS, ',', GX
  FLUSH(ERROR_UNIT)
  IF (N .LT. 1000) THEN
     I = -GS
     DO J = 1, N
        WRITE (ERROR_UNIT,'(I3,A,ES30.21E4)') J, ',', SCALE(REAL(SV(J), REAL128), I)
        FLUSH(ERROR_UNIT)
     END DO
  END IF
END SUBROUTINE XTRACK
