SUBROUTINE XTRACK(N, SV, GX, GS, SWP, NTR)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = 10
  INTEGER, INTENT(IN) :: N, GS, SWP, NTR
  REAL(KIND=K), INTENT(IN) :: SV(N), GX
  INTEGER :: I, J
  WRITE (ERROR_UNIT,'(I10,I11,I7,ES30.21E4)') SWP, NTR, GS, GX
  I = -GS
  DO J = 1, N
     WRITE (ERROR_UNIT,'(I3,ES30.21E4)') J, SCALE(SV(J), I)
  END DO
END SUBROUTINE XTRACK
