#ifdef _OPENMP
SUBROUTINE YCLEAR(N, A)
#else
PURE SUBROUTINE YCLEAR(N, A)
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  COMPLEX(KIND=REAL128), PARAMETER :: ZERO = CMPLX(0.0_REAL128, 0.0_REAL128, REAL128)
  INTEGER, INTENT(IN) :: N
  COMPLEX(KIND=REAL128), INTENT(OUT) :: A(N)
  INTEGER :: I
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I) SHARED(A,N)
  DO I = 1, N
     A(I) = ZERO
  END DO
  !$OMP END PARALLEL DO
END SUBROUTINE YCLEAR
