FUNCTION YDETM1(CS1, SN1)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  REAL(KIND=REAL128), PARAMETER :: ONE = 1.0_REAL128
  REAL(KIND=REAL128), INTENT(IN) :: CS1
  COMPLEX(KIND=REAL128), INTENT(IN) :: SN1
  REAL(KIND=REAL128) :: YDETM1
  YDETM1 = ONE - CS1 * CS1 + REAL(SN1) * REAL(SN1) + AIMAG(SN1) * AIMAG(SN1)
END FUNCTION YDETM1
