PURE FUNCTION YDETM1(CS1, SN1, E)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
  IMPLICIT NONE
  REAL(REAL128), PARAMETER :: MONE = -1.0_REAL128
  REAL(REAL128), INTENT(IN) :: CS1, E
  COMPLEX(REAL128), INTENT(IN) :: SN1
  REAL(REAL128) :: YDETM1
  YDETM1 = IEEE_FMA(CS1, CS1, IEEE_FMA(REAL(SN1), REAL(SN1), IEEE_FMA(AIMAG(SN1), AIMAG(SN1), MONE))) / E
END FUNCTION YDETM1
