! C += A * B
#ifdef _OPENMP
SUBROUTINE YMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#else
PURE SUBROUTINE YMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#endif
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: K = REAL128
  INTEGER, INTENT(IN) :: M, N, LDA, LDB, LDC
  COMPLEX(KIND=K), INTENT(IN) :: A(LDA,M), B(LDB,N)
  COMPLEX(KIND=K), INTENT(INOUT) :: C(LDC,N)
  INTEGER :: I, J, L
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I,J,L) SHARED(A,B,C,M,N)
  DO J = 1, N
     DO L = 1, M
        DO I = 1, N
           C(I,J) = CMPLX(IEEE_FMA(REAL(A(I,L)), REAL(B(L,J)), IEEE_FMA(-AIMAG(A(I,L)), AIMAG(B(L,J)), REAL(C(I,J)))),&
                IEEE_FMA(REAL(A(I,L)), AIMAG(B(L,J)), IEEE_FMA(AIMAG(A(I,L)), REAL(B(L,J)), AIMAG(C(I,J)))), K)
        END DO
     END DO
  END DO
  !$OMP END PARALLEL DO
END SUBROUTINE YMMMSQ
