PURE FUNCTION ZFMA(A, B, C, D)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  COMPLEX(KIND=REAL64), INTENT(IN) :: A, B, C
  REAL(KIND=REAL64), INTENT(IN) :: D
  COMPLEX(KIND=REAL64) :: ZFMA
  ZFMA = (A * B + C) * D
END FUNCTION ZFMA
