PURE FUNCTION ZFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  COMPLEX(KIND=REAL64), INTENT(IN) :: A, B, C
  COMPLEX(KIND=REAL64) :: ZFMA
  ZFMA = A * B + C
END FUNCTION ZFMA
