PURE FUNCTION ZFMA(A, B, C)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_ZFMA(DR, DI, AR, AI, BR, BI, CR, CI)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       IMPLICIT NONE
       REAL(KIND=c_double), INTENT(OUT) :: DR, DI
       REAL(KIND=c_double), INTENT(IN) :: AR, AI, BR, BI, CR, CI
     END SUBROUTINE PVN_ZFMA
  END INTERFACE
  COMPLEX(KIND=REAL64), INTENT(IN) :: A, B, C
  COMPLEX(KIND=REAL64) :: ZFMA
  REAL(KIND=REAL64) :: DR, DI
  CALL PVN_ZFMA(DR, DI, REAL(A), AIMAG(A), REAL(B), AIMAG(B), REAL(C), AIMAG(C))
  ZFMA = CMPLX(DR, DI, REAL64)
END FUNCTION ZFMA
