PURE SUBROUTINE ZINISX(M, N, G, LDG, V, LDV, SV, IX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION ZNRMF(M, X)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       COMPLEX(KIND=REAL64), INTENT(IN) :: X(M)
       REAL(KIND=REAL64) :: ZNRMF
     END FUNCTION ZNRMF
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  INTEGER, INTENT(IN) :: M, N, LDG, LDV
  COMPLEX(KIND=K), INTENT(IN) :: G(LDG,N)
  COMPLEX(KIND=K), INTENT(OUT) :: V(LDV,N)
  REAL(KIND=K), INTENT(OUT) :: SV(N)
  INTEGER, INTENT(OUT) :: IX(N)
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: X, Y
  INTEGER :: I, J
#include "hinisx.f90"
END SUBROUTINE ZINISX
