SUBROUTINE ZLJTU2(A11, A22, A21R, A21I, CS, TNR, TNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     FUNCTION PVN_ZLJEU2(A11, A22, A21R, A21I, CS, TNR, TNI, TG, ES)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_double
       REAL(KIND=c_double), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_double), INTENT(OUT) :: CS, TNR, TNI, TG
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_ZLJEU2
     END FUNCTION PVN_ZLJEU2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22
  REAL(KIND=K), INTENT(INOUT) :: A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CS, TNR, TNI
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: TG
  INTEGER(KIND=c_int) :: ES
#define LJEU2 PVN_ZLJEU2
#include "hljtu2.f90"
END SUBROUTINE ZLJTU2
