SUBROUTINE ZLJU2(A11, A22, A21R, A21I, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, ONE = 1.0_REAL64
  REAL(KIND=REAL64), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=REAL64), INTENT(OUT) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_ZLJEU2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_ZLJEU2(A11, A22, A21R, A21I, CS, SNR, SNI, ES))
  IF (INFO .GE. 0) THEN
     INFO = IAND(INFO, 1)
     IF ((CS .EQ. ONE) .AND. (SNR .EQ. ZERO) .AND. (SNI .EQ. ZERO)) INFO = IOR(INFO, 4)
  END IF
END SUBROUTINE ZLJU2
