SUBROUTINE ZLJV2(A11, A22, A21R, A21I, CH, SHR, SHI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       IMPLICIT NONE
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTERFACE
     FUNCTION PVN_LJV2(A11, A22, A21R, A21I, CH, SHR, SHI, ES) BIND(C,NAME='pvn_zljv2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int, c_double
       REAL(KIND=c_double), INTENT(IN) :: A11, A22, A21R, A21I
       REAL(KIND=c_double), INTENT(OUT) :: CH, SHR, SHI
       INTEGER(KIND=c_int), INTENT(INOUT) :: ES
       INTEGER(KIND=c_int) :: PVN_LJV2
     END FUNCTION PVN_LJV2
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K, ONE = 1.0_K
  REAL(KIND=K), PARAMETER :: CUTTH = 4.0_K / 5.0_K
  REAL(KIND=K), PARAMETER :: CUTCH = 5.0_K / 3.0_K
  REAL(KIND=K), PARAMETER :: CUTSH = 4.0_K / 3.0_K
  REAL(KIND=K), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=K), INTENT(OUT) :: CH, SHR, SHI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=K) :: A
  INTEGER(KIND=c_int) :: ES
  INCLUDE 'hljv2.f90'
END SUBROUTINE ZLJV2
