SUBROUTINE ZLJV2(A11, A22, A21R, A21I, CH, SHR, SHI, INFO)
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       IMPLICIT NONE
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  REAL(KIND=REAL64), PARAMETER :: ZERO = 0.0_REAL64, ONE = 1.0_REAL64
  REAL(KIND=REAL64), PARAMETER :: CUTTH = 4.0_REAL64 / 5.0_REAL64
  REAL(KIND=REAL64), PARAMETER :: CUTCH = 5.0_REAL64 / 3.0_REAL64
  REAL(KIND=REAL64), PARAMETER :: CUTSH = 4.0_REAL64 / 3.0_REAL64
  REAL(KIND=REAL64), INTENT(IN) :: A11, A22, A21R, A21I
  REAL(KIND=REAL64), INTENT(OUT) :: CH, SHR, SHI
  INTEGER, INTENT(INOUT) :: INFO
  REAL(KIND=REAL64) :: A
  INTEGER(KIND=c_int) :: ES
  INTEGER(KIND=c_int), EXTERNAL :: PVN_ZLJV2
  ES = INT(INFO, c_int)
  INFO = INT(PVN_ZLJV2(A11, A22, A21R, A21I, CH, SHR, SHI, ES))
  INCLUDE 'hljv2.f90'
END SUBROUTINE ZLJV2
