! C += A * B
#ifdef _OPENMP
SUBROUTINE ZMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#else
PURE SUBROUTINE ZMMMSQ(M, N, A, LDA, B, LDB, C, LDC)
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M, N, LDA, LDB, LDC
  COMPLEX(KIND=K), INTENT(IN) :: A(LDA,M), B(LDB,N)
  COMPLEX(KIND=K), INTENT(INOUT) :: C(LDC,N)
  INTEGER :: I, J, L
  !$OMP PARALLEL DO DEFAULT(NONE) PRIVATE(I,J,L) SHARED(A,B,C,M,N)
  DO J = 1, N
     DO L = 1, M
        DO I = 1, N
           C(I,J) = ZFMA(A(I,L), B(L,J), C(I,J))
        END DO
     END DO
  END DO
  !$OMP END PARALLEL DO
END SUBROUTINE ZMMMSQ
