PURE FUNCTION ZNRMF(M, X)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       IMPLICIT NONE
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  COMPLEX(KIND=K), PARAMETER :: ZERO = CMPLX(0.0_K, 0.0_K, K)
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(IN) :: X(M)
  REAL(KIND=K) :: ZNRMF
  INTEGER :: I
  ZNRMF = ZERO
  IF (M .LE. 0) RETURN
  ZNRMF = CR_HYPOT(REAL(X(1)), AIMAG(X(1)))
  DO I = 2, M
     ZNRMF = CR_HYPOT(ZNRMF, CR_HYPOT(REAL(X(I)), AIMAG(X(I))))
  END DO
END FUNCTION ZNRMF
