SUBROUTINE ZRN(M, N, A)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: M, N
  REAL(KIND=REAL64), INTENT(OUT) :: A(2*M,N)
  CALL RANDOM_NUMBER(A)
END SUBROUTINE ZRN
