PURE SUBROUTINE ZRTH(M, X, Y, CH, THR, THI, GX, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#ifdef USE_IEEE_INTRINSIC
#define DFMA IEEE_FMA
#else
  INTERFACE
     PURE FUNCTION DFMA(A, B, C) BIND(C,NAME='fma')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN), VALUE :: A, B, C
       REAL(KIND=REAL64) :: DFMA
     END FUNCTION DFMA
  END INTERFACE
#endif
  INTEGER, PARAMETER :: K = REAL64
#define ZFMA(A,B,C) CMPLX(DFMA(REAL(A),REAL(B),DFMA(-AIMAG(A),AIMAG(B),REAL(C))),DFMA(REAL(A),AIMAG(B),DFMA(AIMAG(A),REAL(B),AIMAG(C))),K)
  INTEGER, INTENT(IN) :: M
  COMPLEX(KIND=K), INTENT(INOUT) :: X(M), Y(M)
  REAL(KIND=K), INTENT(IN) :: CH, THR, THI
  REAL(KIND=K), INTENT(INOUT) :: GX
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: TH, HT, XX, YY
  INTEGER :: I
#define HFMA ZFMA
#include "hrth.f90"
END SUBROUTINE ZRTH
