PURE SUBROUTINE ZRTLT(N, A, LDA, AX, P, Q, CS, SNR, SNI, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#include "cr.f90"
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: A(LDA,N)
  REAL(KIND=K), INTENT(INOUT) :: AX
  REAL(KIND=K), INTENT(IN) :: CS, SNR, SNI
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: SN, HS, XX, YY
  INTEGER :: J
#define HFMA ZFMA
#include "hrtlt.f90"
END SUBROUTINE ZRTLT
