PURE SUBROUTINE ZRTRH(N, A, LDA, AX, P, Q, CH, SHR, SHI, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
#ifdef USE_IEEE_INTRINSIC
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_FMA
#endif
  IMPLICIT NONE
#ifdef USE_IEEE_INTRINSIC
#define DFMA IEEE_FMA
#else
  INTERFACE
     PURE FUNCTION DFMA(A, B, C) BIND(C,NAME='fma')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       REAL(KIND=REAL64), INTENT(IN), VALUE :: A, B, C
       REAL(KIND=REAL64) :: DFMA
     END FUNCTION DFMA
  END INTERFACE
#endif
  INTERFACE
     PURE FUNCTION CR_HYPOT(X, Y) BIND(C,NAME='cr_hypot')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
       IMPLICIT NONE
       REAL(KIND=c_double), INTENT(IN), VALUE :: X, Y
       REAL(KIND=c_double) :: CR_HYPOT
     END FUNCTION CR_HYPOT
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
#define ZFMA(A,B,C) CMPLX(DFMA(REAL(A),REAL(B),DFMA(-AIMAG(A),AIMAG(B),REAL(C))),DFMA(REAL(A),AIMAG(B),DFMA(AIMAG(A),REAL(B),AIMAG(C))),K)
  INTEGER, INTENT(IN) :: N, LDA, P, Q
  COMPLEX(KIND=K), INTENT(INOUT) :: A(LDA,N)
  REAL(KIND=K), INTENT(INOUT) :: AX
  REAL(KIND=K), INTENT(IN) :: CH, SHR, SHI
  INTEGER, INTENT(INOUT) :: INFO
  COMPLEX(KIND=K) :: SH, HS, XX, YY
  INTEGER :: I
#define HFMA ZFMA
#include "hrtrh.f90"
END SUBROUTINE ZRTRH
