PURE SUBROUTINE ZSWPXD(N, A, LDA, V, LDV, B, E, INFO)
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE ZSWPC(N, A, LDA, P, Q, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ZSWPC
  END INTERFACE
  INTERFACE
     PURE SUBROUTINE ZSWPR(N, A, LDA, P, Q, INFO)
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, LDA, P, Q
       COMPLEX(KIND=REAL64), INTENT(INOUT) :: A(LDA,N)
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ZSWPR
  END INTERFACE
  INTEGER, PARAMETER :: K = REAL64
  REAL(KIND=K), PARAMETER :: ZERO = 0.0_K
  INTEGER, INTENT(IN) :: N, LDA, LDV, B, E
  COMPLEX(KIND=K), INTENT(INOUT) :: A(LDA,N), V(LDV,N)
  INTEGER, INTENT(OUT) :: INFO
  REAL(KIND=K) :: X, T
  INTEGER :: J
#define SWPC ZSWPC
#define SWPR ZSWPR
#include "hswpxd.f90"
END SUBROUTINE ZSWPXD
