PROGRAM ZTEST
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_double
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: CLAL = 256
  REAL(REAL128), PARAMETER :: QZERO = 0.0_REAL128, QONE = 1.0_REAL128
  CHARACTER(LEN=CLAL) :: CLA
  REAL(c_double), PARAMETER :: HALF = 0.5_c_double
9 FORMAT(A,ES25.17E3)
CONTAINS
#include "orfile.F90"
#include "drsafe.F90"
#include "ydetm1.F90"
#include "qre.F90"
END PROGRAM ZTEST
