SUBROUTINE ZTRKOA(M, N, G, LDG, GS, S, T, U, WRK)
#ifdef __GFORTRAN__
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE
  INTEGER, PARAMETER :: KK = 10
#else
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: REAL64, REAL128
  IMPLICIT NONE
  INTEGER, PARAMETER :: KK = REAL128
#endif
  INTEGER, PARAMETER :: K = REAL64
  INTEGER, INTENT(IN) :: M, N, LDG
  COMPLEX(KIND=K), INTENT(IN) :: G(LDG,N)
  INTEGER, INTENT(IN) :: GS, S
  INTEGER, INTENT(INOUT) :: T, U
  COMPLEX(KIND=KK), INTENT(OUT) :: WRK(M,N)
  CHARACTER(LEN=10) :: FN
  REAL(KIND=K), EXTERNAL :: ZOFFA
  IF ((LDG .LT. M) .OR. (N .LE. 0) .OR. (N .GT. 1000) .OR. (M .LT. N)) RETURN
  IF (S .EQ. 0) THEN
     IF (N .LT. 10) THEN
        WRITE (FN,'(I1)') N
     ELSE IF (N .LT. 100) THEN
        WRITE (FN,'(I2)') N
     ELSE ! N >= 100
        WRITE (FN,'(I3)') N
     END IF
     FN = TRIM(FN)//'zoa.csv'
     OPEN(NEWUNIT=U, IOSTAT=T, FILE=TRIM(FN), STATUS='REPLACE', ACTION='WRITE', ACCESS='SEQUENTIAL', FORM='FORMATTED')
     IF (T .EQ. 0) THEN
        WRITE (U,'(A)') '"TRANSF", "SWEEP", "off(A)"'
        FLUSH(U)
     ELSE ! ERROR
        RETURN
     END IF
  ELSE IF (S .LT. 0) THEN
     CLOSE(U)
     RETURN
  END IF
  WRITE (U,'(I11,A,I3,A,ES25.17E3)') T, ',', S, ',', ZOFFA(M, N, G, LDG, GS, WRK)
  FLUSH(U)
  T = T + 1
END SUBROUTINE ZTRKOA
